### ISSUE TITLE
Support missing values in Boolean columns

### ISSUE THREAD

**Issue by tanguycdls** [laughingman7743/PyAthena#102]
https://github.com/laughingman7743/PyAthena/pull/80
Similar to the above issue, I ran into an issue with missing values in Boolean Columns. When parsing to pandas the conversion fails because we set the dtype to boolean while boolean does not support Na. 

```
pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()
pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_column_data()
pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_tokens()
pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_with_dtype()
ValueError: Bool column has NA values in column 3
```
Could we add a try except Value Error around https://github.com/laughingman7743/PyAthena/blob/d20213533387d473386e32d49bba1cf8616ed253/pyathena/result_set.py#L429 
If it fails we could raise a warning and try again the DataFrame creation with relaxed constraints: 
- Either we follow pandas and convert to object the column involved in the issue (I'm not sure we can detect the faulty column, so we could convert all columns with dtypes that are not Na compatible.)
- Convert booleans (I understand from the PR above that int is already na safe ) to int and warn the user.

If needed I can write a PR once we agree on a solution ! 

Thanks

**Comment by laughingman7743** [comment]
I don't usually use Pandas. I don't know what solution is best.

> [1] Either we follow pandas and convert to object the column involved in the issue (I'm not sure we can detect the faulty column, so we could convert all columns with dtypes that are not Na compatible.)

> [2] Convert booleans (I understand from the PR above that int is already na safe ) to int and warn the user.

Which method do you think is better?

**Comment by laughingman7743** [comment]
Related: https://github.com/laughingman7743/PyAthena/issues/100

**Comment by tanguycdls** [comment]
Hi, thanks for the prompt answer ! I did a PR that respects Pandas Type Promotion so bool will be casted to object dtypes and let the user decide what they want to do with it.

**Comment by laughingman7743** [comment]
Thank you for your PR. I understood what kind of implementation should be done.
I'm thinking of refactoring the Converter class to use it with PandasCursor.
I plan to try it on a weekend.

**Comment by laughingman7743** [comment]
I implemented it so that dtype and converter can be customized freely in the following branches.
Please make sure. 🙏
