### ISSUE TITLE
Struct type to JSON type support

### ISSUE THREAD

**Issue by StdCarrot** [laughingman7743/PyAthena#111]
If struct type on athena is converted to json type on sqlalchemy, it will mush easier to handle data and to make query.
Of course, struct type doesn't 100% matched with json type, but it still handy way to handle struct type if ignore data insertion.
I want to hear your opinion.

**Comment by laughingman7743** [comment]
I think it would be nice to be able to change this mapping freely.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/sqlalchemy_athena.py#L171

The current implementation should be able to change it.
And I could provide methods that can be changed freely.

**Comment by StdCarrot** [comment]
https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.pg_composite

I found Composite Type in PostgreSQL and implementation of it on SQLAlchemy-Utils.  
It almost matched with struct type without type definition.  
It can be modified for Athena's struct type.
