### ISSUE TITLE
Decimal Type not preserved in Parameter Formatting

### ISSUE THREAD

**Issue by EdwardJRoss** [laughingman7743/PyAthena#121]
I expect the Python Decimal type when passed as a parameter in an SQL query to return a Decimal (so there is no loss in precision).

So in the code I expect the last line to return `(Decimal('0.1'),)`, but it returns `(0.1,)`
```
import pyathena
from decimal import Decimal

con = pyathena.connect()

con.cursor().execute('select %(decimal)s', {'decimal': Decimal('0.1')}).fetchone()
```

The reason is the default formatter [just turns it into a string](https://github.com/laughingman7743/PyAthena/blob/master/pyathena/formatter.py#L90)

A workaround is to monkey patch the default formatter:
```
import pyathena
from decimal import Decimal
from pyathena.formatter import DefaultParameterFormatter

def format_decimal(formatter, escaper, val):
    return "DECIMAL {0}".format(escaper(str(val)))

formatter = DefaultParameterFormatter()

formatter._mappings[Decimal] = format_decimal

con = pyathena.connect(formatter=formatter)

con.cursor().execute('select %(decimal)s', {'decimal': Decimal('0.1')}).fetchone()
```

**Comment by laughingman7743** [comment]
Converting Decimal type to string with str as it is may result in exponential format. In that case, the following error occurs.
```
from decimal import Decimal
from pyathena import connect

conn = connect(s3_staging_dir='s3://BUCKET/path/to/',
               region_name='us-west-2')
cursor = conn.cursor()
cursor.execute('select %(decimal)s', {'decimal': Decimal('0.000000001')})
print(cursor.fetchall())
```
```
Traceback (most recent call last):
  File "C:/Users/laughingman7743/github/PyAthena/decimal_test.py", line 9, in <module>
    result = cursor.fetchall()
  File "C:\Users\laughingman7743\github\PyAthena\pyathena\util.py", line 185, in _wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\laughingman7743\github\PyAthena\pyathena\cursor.py", line 57, in execute
    raise OperationalError(query_execution.state_change_reason)
pyathena.error.OperationalError: GENERIC_INTERNAL_ERROR: invalid decimal value '1E-9'
```

**Comment by EdwardJRoss** [comment]
Yes; using `'{:f}.format` instead of `str` is better because it keeps a non-scientific decimal representation.

It will still fail with a "Decimal overflow" if the resulting string has above 38 significant digits (`"select DECIMAL '0." + "1"*39 + "'"`); but I guess this is a case where failing is the right thing to do since it's not supported by the implementation.

**Comment by laughingman7743** [comment]
@EdwardJRoss Thanks! 🙇
