### ISSUE TITLE
Saving ResultSet as a parquet file instead of csv the given s3_staging_dir

### ISSUE THREAD

**Issue by adrianohrl** [laughingman7743/PyAthena#125]
I would like to know if it is possible to save the result set of a given query as a _parquet_ format instead of a _csv_ one.

**Comment by laughingman7743** [comment]
I don't know if the output format of `s3_staging_dir` in Athena can be changed.
Please contact AWS Support or the AWS Forum.

If you want to convert the result set Dataframe to Parquet, you may want to use the `to_sql` method.
https://github.com/laughingman7743/PyAthena#to-sql

**Comment by EdwardJRoss** [comment]
I'd be interested to know if that's possible.

To output a query as Parquet you could wrap it in a [CTAS](https://docs.aws.amazon.com/athena/latest/ug/create-table-as.html)

```
CREATE TABLE parquet_output
WITH (
     format = 'PARQUET', 
) 
AS {query}
```

If you need to find the files you can use

```
SELECT DISTINCT "${path}" from parquet_output
```

Some drawbacks of this approach are:
* all columns in query must be named
* all types must be able to be inferred
* output might be split across multiple files in a way that destroys sorting

The advantage over `to_sql` is you don't need to read everything into memory
