### ISSUE TITLE
Querytimeout issue

### ISSUE THREAD

**Issue by NeelPatel21** [laughingman7743/PyAthena#128]
I am using PyAthena connector with Superset SqlAlchemy. Here I am providing connection-url. It's working correctly for most of the part but I am receiving query-timeout error frequently after waiting for around 30 seconds.

As per the documentation, athena's default query timeout is 30 minutes.
Is there parameter that I can pass in connection url of sqlalchemy to increase default query-timeout?

**Comment by laughingman7743** [comment]
I think that timeout cannot be set in the connection string of SQLAlchemy.
Is it possible that an error has occurred?
Something may have been output to the Superset log.

**Comment by NeelPatel21** [comment]
I am trying to reproduce this issue but it's random & rare.
