### ISSUE TITLE
jpype._jexception.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by arnaudsj** [laughingman7743/PyAthena#13]
Hi,

I am running into this error after running several big queries and reusing the connection:

```
jpype._jexception.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: GC overhead limit exceeded
```
Any ideas? Any way to pass the JVM args to JPype to increase the mem given to the JVM on start?

Thanks!

**Comment by laughingman7743** [comment]
Why do you register this issue for this project?
If it is an issue of the JDBC version, please register to https://github.com/laughingman7743/PyAthenaJDBC/issues and close this issue.

**Comment by arnaudsj** [comment]
Oops, I indeed did file it in the wrong project. My apologies...
