### ISSUE TITLE
Support China region Athena

### ISSUE THREAD

**Issue by liangruibupt** [laughingman7743/PyAthena#134]
# ERROR:
```bash
# awsathena+rest URI
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://athena.athena.cn-northwest-1.amazonaws.com.cn.amazonaws.com/"
```

# FIX
update https://github.com/laughingman7743/PyAthena/blob/master/pyathena/sqlalchemy_athena.py#L233 as below
```python
'region_name': re.sub(r'^athena\.([a-z0-9-]+)\.amazonaws\.(com.cn|com)$', r'\1', url.host),
```

@laughingman7743 Please help fix the issue, I have tested in my project

https://github.com/liangruibupt/covid_19_report_end2end_analytics/blob/master/Athena-Superset-China.md

**Comment by laughingman7743** [comment]
@liangruibupt Thank you!
I just released a new version 1.10.4 to PyPI.
https://pypi.org/project/PyAthena/1.10.4/
