### ISSUE TITLE
Regular expression SQLs with % in cannot be run

### ISSUE THREAD

**Issue by GAwadhwalAtlassian** [laughingman7743/PyAthena#14]
Hi,

I noticed that some basic valid sqls cant be run using pyathena
e.g.
`
SELECT key 
from schema.table
where key like '%greenhopper%'
LIMIT 10`

which normally runs,

gives the following stack trace in pyathena (immediately fails when attempting to parse the %):
`python pyathenatest.py
Traceback (most recent call last):
  File "pyathenatest.py", line 9, in <module>
    cursor.execute(sql)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyathena/util.py", line 29, in _wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyathena/cursor.py", line 213, in execute
    query = self._formatter.format(operation, parameters)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyathena/formatter.py", line 112, in format
    return (operation % kwargs).strip()
TypeError: float argument required, not dict`

I'll have a look myself at the code for that function.

**Comment by laughingman7743** [comment]
if `%` character is contained in your query, it must be escaped with `%%` like the following:
```
SELECT key from schema.table where key like '%%greenhopper%%' LIMIT 10
```
And if you want to avoid escaping `%` characters, you can create a custom formatter class.
```
from pyathenajdbc import connect

class MyFormatter(object):
    def format(self, operation, parameters=None):
        return operation

conn = connect(s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',
               region_name='us-west-2',
               formatter=MyFormatter())
try:
    with conn.cursor() as cursor:
        cursor.execute("""
        SELECT * FROM one_row
        """)
        print(cursor.fetchall())
finally:
    conn.close()
```

**Comment by laughingman7743** [comment]
I fixed the behavior of formatter. Please check the following pull requests.
laughingman7743/PyAthena/pull/16
