### ISSUE TITLE
Extra Single Quotes being added when using parameters

### ISSUE THREAD

**Issue by gabrielsoltz** [laughingman7743/PyAthena#144]
Hi, when using parameters for creating a table, I get extra single quotes added to the name of it: 

```python
   table_name = "test"
    athena.execute("""
                CREATE EXTERNAL TABLE `%(table_name)s` (
               ....
               ....
                   """, {'table_name': table_name})
```

This executes: 
```python
CREATE EXTERNAL TABLE `'test'`
```

Is there a way to avoid this behaviour?

**Comment by laughingman7743** [comment]
Currently, the query parameters are made to be used in the where clause.
I don't expect to parameterize the table name. There is currently no way to avoid single quotes.
