### ISSUE TITLE
InvalidRequestException with quoted dates

### ISSUE THREAD

**Issue by liquidcarbon** [laughingman7743/PyAthena#151]
```
q = """
SELECT * FROM "schema"."table" WHERE "my_date"='2020-07-07' limit 3;
"""
pd.read_sql(q, conn)
```

This query runs and returns the expected Pandas DataFrame, but throws this warning:
```
Failed to execute query.
Traceback (most recent call last):
...
  File ".../lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 13:74: extraneous input '2020' expecting {<EOF>, '.', '[', 'GROUP', 'ORDER', 'HAVING', 'LIMIT', 'AT', 'OR', 'AND', 'UNION', 'EXCEPT', 'INTERSECT', '+', '-', '*', '/', '%', '||'}
```

**Comment by laughingman7743** [comment]
I get the following error.
```
import pandas as pd
import pyathena

conn = pyathena.connect(
    s3_staging_dir="s3://BUCKET/path/to/", region="us-west-2"
)
q = """
SELECT * FROM "default"."one_row_complex" WHERE "col_date"='2020-07-07' limit 3;
"""
df = pd.read_sql(q, conn)
print(df.describe())
```
```
Traceback (most recent call last):
  File "C:\Users\laughingman7743\.virtualenvs\PyAthena-L16IeiG_\lib\site-packages\pandas\io\sql.py", line 1586, in execute
    cur.execute(*args, **kwargs)
  File "C:\Users\laughingman7743\github\PyAthena\pyathena\util.py", line 306, in _wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\laughingman7743\github\PyAthena\pyathena\cursor.py", line 81, in execute
    raise OperationalError(query_execution.state_change_reason)
pyathena.error.OperationalError: SYNTAX_ERROR: line 1:59: '=' cannot be applied to date, varchar(10)
```
It seems that you need to use CAST or DATE literals to compare dates.
```
q = """
SELECT * FROM "default"."one_row_complex" WHERE "col_date"=DATE'2020-07-07' limit 3;
"""
```

**Comment by liquidcarbon** [comment]
```
OperationalError: (pyathena.error.OperationalError) SYNTAX_ERROR: line 2:21: '>' cannot be applied to varchar, date
[SQL: 
SELECT * FROM "prod"."quantum_errors_daily_set_agg"
WHERE "denver_date" = DATE('2020-07-07')
LIMIT 3;
]
```
same with CAST, and no results this time

**Comment by laughingman7743** [comment]
> OperationalError: (pyathena.error.OperationalError) SYNTAX_ERROR: line 2:21: '=' cannot be applied to varchar, date

Isn't the column `my_date` a string type? I get the same error when comparing String and Date types.

```
SELECT * FROM "default"."one_row_complex" 
WHERE "col_string" = DATE('2020-07-07')
LIMIT 3;
```
`SYNTAX_ERROR: line 2:20: '=' cannot be applied to varchar, date`

I think it would be a good idea to run the query in Athena's web console first to see if the error occurs.

**Comment by liquidcarbon** [comment]
I appreciate your responses.
All of our dates are strings.  Rightfully so, comparing string to DATE literal gives an error, but Athena has no issues with `WHERE DATE("my_date") = DATE('2020-07-07')` or simply `WHERE "my_date" = '2020-07-07'`, and neither does PyAthena because it returns the results.

But it's the warning `StartQueryExecution operation: line 13:74: extraneous input '2020' expecting {<EOF>, '.', '[', 'GROUP', 'ORDER', 'HAVING', 'LIMIT', 'AT', 'OR', 'AND', 'UNION', 'EXCEPT', 'INTERSECT', '+', '-', '*', '/', '%', '||'}` that bugs me.

**Comment by laughingman7743** [comment]
Are you saying that the query runs normally but you get a Warning message? I'm not sure what the situation is.
If you don't mind, it might be possible to investigate further if you could share the code you are running.
