### ISSUE TITLE
Feature request: cancel query upon keyboard interrupt

### ISSUE THREAD

**Issue by kaheicanaan** [laughingman7743/PyAthena#153]
When the SQL statement is mis-configured, a large output might generated (which waste plenty of time and resource). Is it a good idea to handle keyboard interrupt (e.g. Ctrl + C) and cancel the corresponding query if it is still running on Athena? I can work on this feature if you think it is appropriate.

**Comment by laughingman7743** [comment]
Implemented in v1.11.0. Please give it a try. 😁
https://github.com/laughingman7743/PyAthena/releases/tag/v1.11.0
https://github.com/laughingman7743/PyAthena/pull/150

**Comment by kaheicanaan** [comment]
Oh sorry for repeated request. I didn't pay much attention on existing issues. Btw, I have tested it manually and it works perfectly! Thanks.
