### ISSUE TITLE
_as_pandas() converts 'NA' to nan - consider adding optional keep_default_na=False argument

### ISSUE THREAD

**Issue by NanisTe** [laughingman7743/PyAthena#154]
'NA' strings in a result in result_set.py are converted to nan by the function _as_pandas().

Consider adding optional argument keep_default_na in the pd.read_csv() inside _as_pandas() function to control behaviour.

This correlates to issue #118 and #120

**Comment by laughingman7743** [comment]
How about allowing the option to keep_default_na, na_values, in the execution method as follows:
https://github.com/laughingman7743/PyAthena/pull/120/commits/660d470f7bbd1e9cc3a5b0f68f10cd3ccf310ffc
```
from pyathena import connect
from pyathena.pandas_cursor import PandasCursor

cursor = connect(s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',
                 region_name='us-west-2',
                 cursor_class=PandasCursor).cursor()

df = cursor.execute("SELECT * FROM many_rows", keep_default_na=False, na_values=[""]).as_pandas()
```

**Comment by NanisTe** [comment]
> How about allowing the option to keep_default_na, na_values, in the execution method as follows:
> [c379656](https://github.com/laughingman7743/PyAthena/commit/c379656ede6cac3585ff991428022bdd38b002ba)
> 
> ```
> from pyathena import connect
> from pyathena.pandas_cursor import PandasCursor
> 
> cursor = connect(s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',
>                  region_name='us-west-2',
>                  cursor_class=PandasCursor).cursor()
> 
> df = cursor.execute("SELECT * FROM many_rows", keep_default_na=False, na_values=[""]).as_pandas()
> ```

Is that an already working solution or do you suggest to implement something like this?
I would keep it in as_pandas() since it is much more related to that than to the query execution itself.

**Comment by laughingman7743** [comment]
> Is that an already working solution or do you suggest to implement something like this?

It is implemented in the following branches. 
https://github.com/laughingman7743/PyAthena/pull/120

> I would keep it in as_pandas() since it is much more related to that than to the query execution itself.

The current implementation is designed to load the CSV automatically after the query is executed, so calling as_pasdas does not load the CSV. The _as_pandas method is called in the constructor of the result_set object.
I don't want to make any major changes to this implementation.
