### ISSUE TITLE
Missing records when writing to Athena

### ISSUE THREAD

**Issue by RiccardoDiGuida** [laughingman7743/PyAthena#158]
I am not 100% sure this is related to PyAthena but this is my best guess.

When I write some pandas df to Athena it either writes the wrong number of records (less then expected) or ignores the `if_exists='replace'` parameter.

Specifically:

```python
import pandas as pd
from sqlalchemy import create_engine


us = pd.read_csv('example.csv') #It has 43228 rows (checked also in the debugger)

ath_engine = create_engine(
        f"""awsathena+rest://{ath_info_['aws_access_key_id']}:{ath_info_['aws_secret_access_key']}"""
        f"""@athena.{ath_info_['region_name']}.amazonaws.com:443/"""
        f"""{ath_info_['schema_name']}?s3_staging_dir={ath_info_['s3_writing_dir']}"""
        f"""&s3_dir={ath_info_['s3_writing_dir']}&compression=snappy""")
us .to_sql('st_table', ath_engine, schema=ath_info_['schema_name'], index=False,
                        if_exists='replace', chunksize=1000, method='multi')
```

The first time I ran this query I executed a `COUNT` and I got 33000 rows. So I executed the same code again and now I got 76228 records which means the whole table was appended to the previous writing (hence the `replace` was ignored).

I also wrote another table (far bigger) and only around 2% of records were written (exactly 37000)

**Comment by laughingman7743** [comment]
Athena doesn't delete data in S3 when you delete a table, which is probably why the replace parameter doesn't work as well as it should.
