### ISSUE TITLE
Getting HIVE_FILESYSTEM_ERROR: Error reading from s3://xy at position z

### ISSUE THREAD

**Issue by pederpansen** [laughingman7743/PyAthena#173]
I'm getting reproducable errors:

```
File "/usr/local/lib/python3.7/site-packages/pyathena/pandas_cursor.py", line 88, in execute
    raise OperationalError(query_execution.state_change_reason)
pyathena.error.OperationalError: HIVE_FILESYSTEM_ERROR: Error reading from s3://tables/my-table/date=20201103/20201105_130221_00046_qwjw6_1fa9f6a5-3c40-432a-9424-060412402d1f at position 4352858
```

If I copy the referenced file from S3 and open it locally via `parquet-tools`, it works fine. Running the same query in the Athena UI also works without problems.

What does this error mean?

**Comment by laughingman7743** [comment]
It doesn't seem to be an error in the Python library, so I don't know what's causing it.
Is it possible that the schema in the Athena table definition and the Parquet file don't match, or that the partition is not recognized (not running MSK REPAIR TABLE), etc.?

**Comment by pederpansen** [comment]
Might be... the error did not appear again today when run with slightly different data. I will close this issue as non-reproducable.
