### ISSUE TITLE
cannot import name as_pandas

### ISSUE THREAD

**Issue by vitortoledo93** [laughingman7743/PyAthena#178]
With 2.0.0 release at my code i had in my import lines:

`from pyathena.util import as_pandas`

and got the error message : 

> cannot import name as_pandas

like in the below screenshot:

![image](https://user-images.githubusercontent.com/26752151/98627982-42063600-22f4-11eb-915c-9c8ffb606565.png)

After removing this line and just executed the rest of my code everything has gone fine, i'm supposing that now we don't need to import as_pandas to use inside the code, that we have this done implicitly but in the new Pyathena release documentation it's saying that we can do it, you can check in this below url and find for:  

>  as_pandas

[https://pypi.org/project/pyathena/2.0.0/](url)

 Can you check it please, thank you, sorry for my bad english, that's alot of time that i didnt write nothing in english.

Vitor Toledo.

**Comment by laughingman7743** [comment]
I moved it from 2.0 to the `pyathena.pandas` package. Please try the following import statement.
```
from pyathena.pandas.util import as_pandas
```

**Comment by vitortoledo93** [comment]
Hello @laughingman7743 thanks for the fast answer, we can import "as_pandas" using:

`from pyathena.pandas.util import as_pandas`

if you guys can correct PyAthena 2.0 documentation to reflect this change would be very nice.

Thank you again
