### ISSUE TITLE
Updating readme to encourage better security credential management

### ISSUE THREAD

**Issue by l1x** [laughingman7743/PyAthena#181]
Hi,

I was wondering if you would be open to change the README and related docs around and get rid off encouraging putting credentials into source code.

BAD:

As the name implies secret key should be kept secret and not put in to source code / version control / etc.

```Python
from pyathena import connect
cursor = connect(aws_access_key_id="YOUR_ACCESS_KEY_ID",
                 aws_secret_access_key="YOUR_SECRET_ACCESS_KEY",
                 s3_staging_dir="s3://YOUR_S3_BUCKET/path/to/",
                 region_name="us-west-2").cursor()
cursor.execute("SELECT * FROM one_row")
```

GOOD:

Using the profile in 

```Python
from pyathena import connect
import boto3
dev = boto3.session.Session(profile_name='aws-profile')
creds = dev.get_credentials()
cursor = connect(
    aws_access_key_id=creds.access_key,
    aws_secret_access_key=creds.secret_key,
    s3_staging_dir='s3://bucket/athena-tmp/',
    region_name='eu-west-1'
).cursor()
```

If you are inclined to switch it up I can send you a PR.

Thank you in advance.

**Comment by laughingman7743** [comment]
You may want to specify the `profile_name` as an argument to the connect method.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L58
```
from pyathena import connect
cursor = connect(
    profile_name='aws-profile'
    s3_staging_dir='s3://bucket/athena-tmp/',
    region_name='eu-west-1'
).cursor()
```

**Comment by laughingman7743** [comment]
Please refer to the Credentails section.
https://github.com/laughingman7743/PyAthena#credentials
> Credentials
>
> Support Boto3 credentials.
>
> Additional environment variable:
>
> $ export AWS_ATHENA_S3_STAGING_DIR=s3://YOUR_S3_BUCKET/path/to/
> $ export AWS_ATHENA_WORK_GROUP=YOUR_WORK_GROUP

**Comment by l1x** [comment]
Thanks, the question still stands. Would you be ok update the documentation?

**Comment by laughingman7743** [comment]
Yes, improvements in documentation are welcome.

**Comment by l1x** [comment]
Thanks, submitted.
