### ISSUE TITLE
`as_pandas` not in `pyathena.util` anymore

### ISSUE THREAD

**Issue by tmayer** [laughingman7743/PyAthena#183]
When following the documentation with PyAthena 2.0.0 the code working with pandas (e.g., `as_pandas`) doesn't work anymore as the function is no longer in the pyathena.util module:

`from pyathena.util import as_pandas`

throws an error

`ImportError: cannot import name 'as_pandas'`

Thanks for addressing the issue!

**Comment by laughingman7743** [comment]
Please try the following import statement.
```
from pyathena.pandas.util import as_pandas
```
https://github.com/laughingman7743/PyAthena/issues/179
https://github.com/laughingman7743/PyAthena/issues/178

**Comment by tmayer** [comment]
yes, that works! It was more directed towards the documentation that needs to be updated. But I didn't see the closed issue. Thanks for the quick reply and the great package!
