### ISSUE TITLE
Cache Expiration Based on Time

### ISSUE THREAD

**Issue by rubenssoto** [laughingman7743/PyAthena#187]
Hello,

Athena cache is a great feature, but is it possible to set a cache expiration based on time?

Thank you

**Comment by laughingman7743** [comment]
The response to `batch_get_query_execution` contains information about the date and time the query was completed,
so I think it can be implemented.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html#Athena.Client.batch_get_query_execution

**Comment by laughingman7743** [comment]
I am trying to implement it in the following branch.
https://github.com/laughingman7743/PyAthena/pull/201
Please check it out.

**Comment by rubenssoto** [comment]
Thank you so much!! I will use this feature with redash

**Comment by rubenssoto** [comment]
To give you some ideas,

It would be good, have two options for example:

cursor.execute(query, inspect_last_queries= 60, expiration_time= 20 minutes)

inspect_last_queries is the number of X queries that pyathena should inspect in cache
and expiration_time is the time filter...

**Comment by laughingman7743** [comment]
It can be achieved with the already implemented cache_size option. 😁 
https://github.com/laughingman7743/PyAthena#quickly-re-run-queries
`cache_size` and `cache_expiration_time` can be specified simultaneously.
```
cursor.execute(query, cache_size=60, cache_expiration_time=1200)
```

**Comment by afparsons** [comment]
@laughingman7743 In PR #519, you added the following line to the documentation in bold text:

> Please use the Result reuse configuration.

1. Both caches can be used; should a user _only_ use one?
2. Could you explain why users should use the AWS Athena result reuse instead of local caching? 
3. Do you plan to deprecate the caching feature added in PR #201?

**Comment by laughingman7743** [comment]
> 1. Both caches can be used; should a user only use one?
No, you can use either. Use whichever suits your use case.

> 2. Could you explain why users should use the AWS Athena result reuse instead of local caching?
PyAthena's own cache implementation can cause performance problems, as in the following issue.
https://github.com/laughingman7743/PyAthena/issues/209

> 3. Do you plan to deprecate the caching feature added in PR
I am not planning to deprecate this feature at this time.
