### ISSUE TITLE
passing 'verify=False' in the connection string gives No such file or directory

### ISSUE THREAD

**Issue by tamersalama** [laughingman7743/PyAthena#188]
Passing verify=False in the connection string results in the error below
```(pyathena.error.DatabaseError) SSL validation failed for https://athena.us-west-2.amazonaws.com/ [Errno 2] No such file or directory```

It looks like False is interpreted as a string literal - to which one of the base libraries is trying to navigate.

`verify` is a valid `_CLIENT_PASSING_ARGS`

**Comment by laughingman7743** [comment]
It happens when I specify "verify" in the SQLAlchemy connection string.

**Comment by laughingman7743** [comment]
Fixed in the following branch.
https://github.com/laughingman7743/PyAthena/pull/193
Please check it out.

**Comment by tamersalama** [comment]
Thank you for your work on the project and for the quick resolution of the issue.
