### ISSUE TITLE
SQLAlchemy dependency ignored when installing 2.0.0

### ISSUE THREAD

**Issue by Akeboshiwind** [laughingman7743/PyAthena#189]
This is easiest to show with an example:
```bash
$ mkdir /tmp/test
$ cd /tmp/test
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ echo 'PyAthena[SQLAlchemy]>=2.0.0' > requirements.txt
(venv) $ pip3 install -r requirements.txt 2>/dev/null | grep Ignoring
  Ignoring sqlalchemy: markers 'extra == "SQLAlchemy"' don't match your environment
```

As you can see, SQLAlchemy isn't installed if you specify the "SQLAlchemy" extra on 2.0.0.

I've confirmed that this isn't an issue if I specify `PyAthena[SQLAlchemy]==1.11.2` instead.

**Comment by laughingman7743** [comment]
Thanks, I guess the change of package manager to Poetry from 2.0.0 has an effect.
I will investigate.

**Comment by Akeboshiwind** [comment]
Yeah, that's likely the cause

**Comment by laughingman7743** [comment]
https://github.com/pypa/pip/issues/4617 👀

**Comment by laughingman7743** [comment]
I uploaded version 2.0.1 of the following branch to test.pypi.org.
https://github.com/laughingman7743/PyAthena/pull/191
https://test.pypi.org/project/pyathena/2.0.1/

I installed it to try it out and it seemed to work fine :)
Please check it out.
