### ISSUE TITLE
Support for EndpointOverride

### ISSUE THREAD

**Issue by chrisbulgaria** [laughingman7743/PyAthena#192]
First thanks for the great work - much appreciated.

This one - as opposed to pyathenajdbc does not appear to support the use of an Endpointoverride ? Neither as parameter, nor as replacement of the url itself (using the sqlalchemy connection string).  But maybe Im overlooking something.

Would be great to support it. 

Cheers,
Chris

**Comment by laughingman7743** [comment]
The values of the following arguments specified in the connect method are passed to the boto3 client.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L38-L47

I haven't tried it, but you can probably override it by specifying endpoint_url as follows.
```
conn= connect(s3_staging_dir="s3://YOUR_S3_BUCKET/path/to/",
              region_name="us-west-2"
              endpoint_url="[vpce-specific-url].athena.[Region].vpce.amazonaws.com:443")
```
