### ISSUE TITLE
Minimum required IAM permissions 

### ISSUE THREAD

**Issue by KentonParton** [laughingman7743/PyAthena#205]
Hello,

I will be using PyAthena with the following format `awsathena+rest://:@athena.{region_name}.amazonaws.com:443/{schema_name}?s3_staging_dir={s3_staging_dir}&...
`

What are the minimum AWS IAM actions required to use PyAthena? Also, does the role require access to the underlying S3 bucket? For example, if I have an Athena table in some S3 bucket, does the Instance Profile role require access to the S3 resource or just to Athena?

Appreciate the help.

**Comment by laughingman7743** [comment]
The IAM permission settings will depend on your use case.
For example, the IAM account that runs CI for this repository has the following permission settings.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "glue:BatchCreatePartition",
                "glue:UpdateDatabase",
                "glue:CreateTable",
                "glue:DeleteDatabase",
                "glue:GetTables",
                "glue:GetPartitions",
                "glue:BatchDeletePartition",
                "glue:UpdateTable",
                "glue:BatchGetPartition",
                "glue:DeleteTable",
                "athena:*",
                "glue:GetDatabases",
                "glue:GetTable",
                "glue:GetDatabase",
                "glue:GetPartition",
                "glue:CreateDatabase",
                "glue:BatchDeleteTable",
                "glue:CreatePartition",
                "glue:DeletePartition",
                "glue:UpdatePartition"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucketMultipartUploads",
                "s3:AbortMultipartUpload",
                "s3:CreateBucket",
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:GetBucketLocation",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": "arn:aws:s3:::MY_S3_BUCKET"
        }
    ]
}
```
I think you should refer to the official documentation.
https://docs.aws.amazon.com/athena/latest/ug/security-iam-athena.html

**Comment by KentonParton** [comment]
Thanks @laughingman7743. I am using it in Apache Superset to execute Athena queries.

**Comment by laughingman7743** [comment]
Here is an example of a metabase configuration, but I think it might be helpful.
https://github.com/dacort/metabase-athena-driver#example-iam-policy

Or you can ask questions on StackOverflow or AWS Forums.
https://stackoverflow.com/
https://forums.aws.amazon.com/index.jspa

I don't use Superset, so I don't know.

**Comment by KentonParton** [comment]
That role looks great, thank you.
