### ISSUE TITLE
Creates meta data in bulk parquet that can not be read

### ISSUE THREAD

**Issue by bprazen** [laughingman7743/PyAthena#208]
When reading from a parquet folder, I get one successful query, but meta data is produced during this query (csv file and a csv.metadata file) which prevents the Athena UI or pyathena from doing another query.  When meta files are removed Athena UI can do queries and pyathena can do one query.

Error message:
OperationalError: HIVE_CANNOT_OPEN_SPLIT: Error opening Hive split s3://XXXX.csv.metadata (offset=0, length=436): Not valid Parquet file: s3://XXX.csv.metadata expected magic number: [80, 65, 82, 49] got: [72, 3, 80, 1]

run using pyathena connect and pandas read_sql

**Comment by bprazen** [comment]
disregard.  I see it now.

**Comment by laughingman7743** [comment]
I think your s3_staging_dir setting is wrong, and the problem is that you are specifying the same location as the S3 where the data of the table to be SELECTed is stored.

**Comment by bprazen** [comment]
Yes, that was my mistake.  Thank you for the quick reply.
