### ISSUE TITLE
Large performance degradation in PyAthena with caching enabled

### ISSUE THREAD

**Issue by INRIX-Trang-Nguyen** [laughingman7743/PyAthena#209]
The search for cached query results using ListQueryExecution is very slow because it has to traverse through all queries executed in the current workgroup. Are there other options to postfilter the data taking the staging directory into consideration?

**Comment by INRIX-Trang-Nguyen** [comment]
I dug more into the performance degradation and confirmed that the root cause is due to the loop on ListQueryExecution to find previous query ids. Since AWS restricts the max limit to 50, the looping results in large network overhead. Unless AWS changes their limit, the current limit makes the caching unusable.

I disabled the caching feature altogether and query performance is now [stable.]([url](url))
![PyAthenaCacheDegradation_ListQueryExecutions](https://user-images.githubusercontent.com/9421899/106404731-86cbd580-63e8-11eb-9a09-2aa98a821537.png)

Additional stats (with the original caching turned on):

[INFO]	2021-02-01T01:03:34.581Z	e4cda1a5-668c-415a-b870-28a6104311fa	        Athena query total_execution_time 1.858 sec,"        service_processing_time: 0.026,        query_queue_time: 0.121,        state: SUCCEEDED,        submission_date_time: 2021-01-31 03:37:02.291000+00:00,        completion_date_time: 2021-01-31 03:37:04.149000+00:00,        data_scanned_in_bytes: 3319334,        output_location: s3://inrix-athena/athena-stage-qa/intersection-metrics-api/performance-metrics/ds=05df3d46-adf5-4af6-9854-aae3163b6e35/2021-01-13/1de432e6-e0e5-43fa-8b4a-6b6308476c6b.csv, | [INFO] 2021-02-01T01:03:34.581Z e4cda1a5-668c-415a-b870-28a6104311fa **Athena query total_execution_time 1.858 sec**," service_processing_time: 0.026, query_queue_time: 0.121, state: SUCCEEDED, submission_date_time: 2021-01-31 03:37:02.291000+00:00, completion_date_time: 2021-01-31 03:37:04.149000+00:00, data_scanned_in_bytes: 3319334, output_location: s3://inrix-athena/athena-stage-qa/intersection-metrics-api/performance-metrics/ds=05df3d46-adf5-4af6-9854-aae3163b6e35/2021-01-13/1de432e6-e0e5-43fa-8b4a-6b6308476c6b.csv,
-- | --
  | 2021-01-31T17:03:34.582-08:00Copy[INFO]	2021-02-01T01:03:34.581Z	e4cda1a5-668c-415a-b870-28a6104311fa	Pyathena total execution time in secs: 67.51300381699912 | [INFO] 2021-02-01T01:03:34.581Z e4cda1a5-668c-415a-b870-**28a6104311fa Pyathena total execution time in secs: 67.51300381699912**

**Comment by laughingman7743** [comment]
Yes, the maximum value for MaxResults in ListQueryExecutions is 50, and I can't filter by anything other than Workgroup.
Is there another better way?

**Comment by INRIX-Trang-Nguyen** [comment]
I checked with AWS support today, and looks like no. I suggest we both put in a request to ask whether they can increase the limit or provide a way to better filter results. Another possibility is to allow a hook to an in-memory DB for mapping query hashes to query ids.

**Comment by laughingman7743** [comment]
Athena engine version 3 can reuse the results of previous queries; you can use that feature starting from v2.18.0, so you may want to use that.
- https://aws.amazon.com/jp/blogs/big-data/reduce-cost-and-improve-query-performance-with-amazon-athena-query-result-reuse/
- https://github.com/laughingman7743/PyAthena/pull/392
- https://github.com/laughingman7743/PyAthena#result-reuse-configuration
- https://github.com/laughingman7743/PyAthena/releases/tag/v2.18.0
