### ISSUE TITLE
Infinity value in double column throws TypeError

### ISSUE THREAD

**Issue by austinlostinboston** [laughingman7743/PyAthena#210]
I recently stumbled into an edge case that was very time consuming to track down, where an infinity value in a double column would throw the exceptions below.

**Problem:**
While running a `select * ...` on an athena table, I would receive the following two errors.
`TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'`
and
`ValueError: cannot safely convert passed user dtype of float64 for object dtyped data in column 19`

**Diagnosis**
At first, I thought these errors were attributed to null values, like the issues brought up in [issue 169](https://github.com/laughingman7743/PyAthena/issues/169). However, excluding null values in my query didn't resolve the issue. After spending a few hours looking over the underlying data for the table, I had found that in a few islolated cases, a calculated column was allowing a division of zero, creating infitinty values.

**Recommendations**

1. Troubleshooting this issue would have been much easier if more args/kwargs from [`pandas.read_csv()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) were accepted by `cursor.execute()`, the `na_filter` kwarg being one of them. It would also be nice to pass `parse_dates` and other `pandas.read_csv()` kwargs. Perhaps you could open this method up to accept and pass user specific kwargs?
2. There is an inherent issue of pyathena not supporting the native athena/presto value of infinity. My guess is this would be fixed by adding a converter for it in `pyathena.converter`.

**Comment by laughingman7743** [comment]
> Troubleshooting this issue would have been much easier if more args/kwargs from pandas.read_csv() were accepted by cursor.execute(), the na_filter kwarg being one of them. It would also be nice to pass parse_dates and other pandas.read_csv() kwargs. Perhaps you could open this method up to accept and pass user specific kwargs?

Yes, it certainly looks like using kwargs would be a good idea.

Is it possible to share a query that can easily reproduce the error in a form like `SELECT values` or `SELECT * FROM (VALUES ('values'))`?

**Comment by austinlostinboston** [comment]
Sure, it looks like adding an infinity value to the query triggers the same error for me. So something like below should replicate the issue.

`select *, inifinity() from table;`

**Comment by laughingman7743** [comment]
If I don't add the read_csv option, I don't get the error. Please tell me the query that causes the error.
```
from pyathena import connect
from pyathena.pandas.cursor import PandasCursor

cursor = connect(s3_staging_dir="s3://BUCKET/path/to/",
                 region_name="us-west-2",
                 cursor_class=PandasCursor).cursor()
cursor.execute("select infinity()")
df = cursor.as_pandas()
print(df.describe())
```
```
       _col0
count    1.0
mean     inf
std      NaN
min      inf
25%      NaN
50%      NaN
75%      NaN
max      inf
```
