### ISSUE TITLE
Athena support TIMESTAMP_MICROS

### ISSUE THREAD

**Issue by rubenssoto** [laughingman7743/PyAthena#212]
Hello,

Aws athena doesn't support TIMESTAMP_MICROS, but there is a workaround hahaha

from_unixtime(to_unixtime(timestamp_col)/1000)

So it is not so good all users have to use this function, is there any way to pyathena apply this correction automatically?

thank you

**Comment by laughingman7743** [comment]
I don't want to support such a function.
