### ISSUE TITLE
Assume Role & MFA for SQLAlchemy

### ISSUE THREAD

**Issue by acountrec** [laughingman7743/PyAthena#213]
Now I don't know if this is either not well documented or not possible but I would like to assume a role and maybe use MFA with SQL Alchemy. Is this possible?

**Comment by acountrec** [comment]
This is issue can be closed. For those wondering how to do it, it's as simple as adding the parameters in de url like this:

`awsathena+rest://{aws_access_key_id}:{aws_secret_access_key}@athena.{region_name}.amazonaws.com:443/{schema_name}?s3_staging_dir={s3_staging_dir}&&role_arn={role_arn}&role_session_name={role_session_name}&serial_number={serial_number}`

**Comment by laughingman7743** [comment]
It would be a good idea to include this in the README.
