### ISSUE TITLE
DurationSeconds in SQLAlchemy

### ISSUE THREAD

**Issue by acountrec** [laughingman7743/PyAthena#214]
Hi,

```
conn_str = f"awsathena+rest://{aws_access_key_id}:{aws_secret_access_key}@athena.{region_name}.amazonaws.com:443/?"\
           f"s3_staging_dir={s3_staging_dir}&role_arn={role_arn}&role_session_name={role_session_name}"\
           f"&serial_number={serial_number}&duration_seconds={duration_seconds}"
```

adding the argument duration_seconds in the SQL Alchemy connection string gives the following error:
```
Invalid type for parameter DurationSeconds, value: 10800, type: <class 'str'>, valid types: <class 'int'>
```

Which is not weird because they expect a int as option, however this is not something I think you can accomplish.
I guess there should be a check if it's possible to parse the string to an int or change the argument to a str in the end

Hope you understand the problem.

**Comment by laughingman7743** [comment]
Probably the same problem as this issue.
https://github.com/laughingman7743/PyAthena/issues/188

**Comment by laughingman7743** [comment]
In addition to `duration_seconds`, I also need to convert `poll_interval` and `kill_on_interrupt` from strings.
