### ISSUE TITLE
init cursor from previously run query_id

### ISSUE THREAD

**Issue by moshir** [laughingman7743/PyAthena#218]
We have an application where we'd like to restore results from previous Athena queries.
If a user has run a query, we store the query id, and we'd like to use pyAthena to open a previously run query.
Is there any way this can be acieved from pyAthena, like initializing the cursor with a query_id ?

**Comment by laughingman7743** [comment]
I don't know if this will fit your use case, but there is a mechanism to use the cache.
https://github.com/laughingman7743/PyAthena#quickly-re-run-queries

**Comment by moshir** [comment]
Unfortunately, i have a query id, want to use the pyAthena parser to restore the results. Looking at the code, it seems the AthenaResultSet class is supposed to do that. I tried the following : 
```
connection = connect(
        aws_access_key_id=creds.access_key,
        aws_secret_access_key=creds.secret_key,
        aws_session_token=creds.token,
        work_group="primary",
        s3_staging_dir=f"s3://somewhereinthecloud/",
        region_name="eu-west-1",
        cursor_class=AsyncCursor
    )
    query_execution=cursor._poll(query_id)
    if query_execution.state== AthenaQueryExecution.STATE_SUCCEEDED:
        result_set.AthenaResultSet(
            connection=connection,
            converter=Converter,
            query_execution=query_execution,
            arraysize=cursor.arraysize,
            retry_config=cursor._retry_config
        )
```

But this fails with 
````
  File "lib/python3.7/site-packages/pyathena/result_set.py", line 371, in <listcomp>
    for meta, row in zip(self._meta_data, rows[i].get("Data", []))
TypeError: convert() missing 1 required positional argument: 'value'
```

**Comment by laughingman7743** [comment]
PyAthena calls this API in boto3 and parses the results.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html#Athena.Client.get_query_results
You may want to call this API and check the results.

**Comment by moshir** [comment]
Sure, but did not want to go back to boto3, NextTokens ... The hack in my previous message almost works. Cant figure out why convert fails.

**Comment by laughingman7743** [comment]
I see. I think your hack method seems to be fine. 😁 
I'm wondering how much of the past execution history Athena can retain. 🤔

**Comment by laughingman7743** [comment]
Also, is there any case that the query result output to s3_staging_dir is not left behind?
