### ISSUE TITLE
Support for Catalog

### ISSUE THREAD

**Issue by milanaleksic** [laughingman7743/PyAthena#220]
I have noticed that PyAthena currently assumes only `Database` is enough as part of the [StartQueryExecution API call](https://docs.aws.amazon.com/athena/latest/APIReference/API_StartQueryExecution.html): https://github.com/laughingman7743/PyAthena/blob/e4a74ddfd7d976a968e18e83d89487f020ec48a6/pyathena/common.py#L185

Would it be possible to consider adding `Catalog` as well in case non-default data source (`AwsDataCatalog`) is used?

**Comment by laughingman7743** [comment]
I see, I think we should support catalogs as well. I'll check it out this weekend.

**Comment by laughingman7743** [comment]
The following branch is now supported. The database name does not need to be specified either, so I changed it to optional.
Please check it out. 🙏 
https://github.com/laughingman7743/PyAthena/pull/221
