### ISSUE TITLE
DeprecationWarning on sqlalchemy's engine.connect() to Athena using pyathena

### ISSUE THREAD

**Issue by esegal** [laughingman7743/PyAthena#225]
When I connect to a PyAthena SQLAlchemy engine (using `engine.connect()`) I get this warning:

`DeprecationWarning: the imp module is deprecated in favour of importlib`

My traceback led me here: `pyathena\util.py", line 17, in <module> from past.builtins import xrange`

pyathena==1.11.5

**Comment by laughingman7743** [comment]
Since Python 2.7 is no longer supported, I will not be updating the version 1.x series that supports Python 2.7.
I recommend that you update to version 2.x series.

**Comment by esegal** [comment]
Thanks for the quick reply! Will do.

**Comment by esegal** [comment]
I just noticed that as an SQLAlchemy dependency, version 2 is not available. Any suggestions?
