### ISSUE TITLE
Query is generating a lot of nulls

### ISSUE THREAD

**Issue by fabioaraujopt** [laughingman7743/PyAthena#235]
While trying to use the tool, I found that the data retreived by the cursor is full on null values although the values are not null...

Part of athena content retrieved from aws console:

1 | 7552 | 5.950448020833334 | 1 | -15.123608938180812 | -4.308211475597302 | 31.155615281149288 | 5579.0 | 14515.0 | -176.6 | 1380.5 (...)

Part of Cursor Fetch all obtained in python:

(None, None, None, None, None, '"8.602100966916987"', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '"0.007173000000000001"', '"5.12307e-05"', None, None, None, None, None, '"0.04079947600898376"', None, None, '"-0.03849830357141969"', None, None, None, None, None, None, None, '"0.00211707408487376"', None, '"UNKNOWN"', None, None, None, None, None, None, None, None, None, None, None, '"0.00140562"', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '"129.4309510080351"', '"737347.1252253413"', '"4.42992293210681e+16"', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)

This is a huge table with about 100 columns.. how should this work?

**Comment by laughingman7743** [comment]
Could you share the table definition and the Python code you are running?

**Comment by fabioaraujopt** [comment]
Hey the table definition is the following 

1 | event_id | bigint
2 | time_to_tca | double
3 | mission_id | bigint
4 | risk | double
5 | max_risk_estimate | double
6 | max_risk_scaling | string
7 | miss_distance | double   
8 | relative_speed | double   
9 | relative_position_r | double   
10 | relative_position_t | double   
11 | relative_position_n | double   
12 | relative_velocity_r | double   
13 | relative_velocity_t | double   
14 | relative_velocity_n | double   
15 | t_time_lastob_start | double   
16 | t_time_lastob_end | double   
17 | t_recommended_od_span | double   
18 | t_actual_od_span | double   
19 | t_obs_available | bigint   
20 | t_obs_used | bigint   
21 | t_residuals_accepted | double   
22 | t_weighted_rms | double 
23 | t_rcs_estimate | double 
24 | t_cd_area_over_mass | double 
25 | t_cr_area_over_mass | string 
26 | t_sedr | string 
27 | t_j2k_sma | double 
28 | t_j2k_ecc | double   
29 | t_j2k_inc | double   
30 | t_ct_r | double   
31 | t_cn_r | double   
32 | t_cn_t | string   
33 | t_crdot_r | double   
34 | t_crdot_t | double   
35 | t_crdot_n | string   
36 | t_ctdot_r | double   
37 | t_ctdot_t | double   
38 | t_ctdot_n | double   
39 | t_ctdot_rdot | double   
40 | t_cndot_r | double   
41 | t_cndot_t | double   
42 | t_cndot_n | double   
43 | t_cndot_rdot | string   
44 | t_cndot_tdot | double   
45 | c_object_type | string   
46 | c_time_lastob_start | double   
47 | c_time_lastob_end | double   
48 | c_recommended_od_span | double   
49 | c_actual_od_span | double   
50 | c_obs_available | double   
51 | c_obs_used | double   
52 | c_residuals_accepted | double   
53 | c_weighted_rms | double   
54 | c_rcs_estimate | double   
55 | c_cd_area_over_mass | double   
56 | c_cr_area_over_mass | double   
57 | c_sedr | string   
58 | c_j2k_sma | double   
59 | c_j2k_ecc | double   
60 | c_j2k_inc | double   
61 | c_ct_r | double   
62 | c_cn_r | double   
63 | c_cn_t | double   
64 | c_crdot_r | double   
65 | c_crdot_t | double   
66 | c_crdot_n | double   
67 | c_ctdot_r | double   
68 | c_ctdot_t | double   
69 | c_ctdot_n | double   
70 | c_ctdot_rdot | double   
71 | c_cndot_r | double   
72 | c_cndot_t | double   
73 | c_cndot_n | double   
74 | c_cndot_rdot | double   
75 | c_cndot_tdot | double   
76 | t_span | double   
77 | c_span | double   
78 | t_h_apo | double   
79 | t_h_per | double   
80 | c_h_apo | double   
81 | c_h_per | double   
82 | geocentric_latitude | double   
83 | azimuth | double   
84 | elevation | double   
85 | mahalanobis_distance | string   
86 | t_position_covariance_det | string   
87 | c_position_covariance_det | string   
88 | t_sigma_r | double   
89 | c_sigma_r | double   
90 | t_sigma_t | double   
91 | c_sigma_t | double   
92 | t_sigma_n | double   
93 | c_sigma_n | double   
94 | t_sigma_rdot | double   
95 | c_sigma_rdot | double   
96 | t_sigma_tdot | double   
97 | c_sigma_tdot | double   
98 | t_sigma_ndot | double   
99 | c_sigma_ndot | double   
100 | f10 | double

The python code being run is the following:

`from pyathena import connect

cursor = connect(s3_staging_dir="s3://YOUR_S3_BUCKET/path/to/",
                 region_name="us-west-2").cursor()
cursor.execute("""
               SELECT * from train_data
               """)
print(cursor.fetchall())
`

**Comment by cansjt** [comment]
Maybe the Athena Console has a feature that hides empty columns, in its preview. But I doubt you previewed the whole data set. And I would guess, would you download the result in a CSV file you would get the same empty columns.

But as far as PyAthena is concerned, it did the right thing and is working as it is supposed to. You used a `SELECT *` so, as any SQL database would do, each column lacking a value in a row was filled with a NULL. You might want to restrict the select-list to only the columns that you know are not empty.
