### ISSUE TITLE
Pandas to_sql with single quoted strings

### ISSUE THREAD

**Issue by bertop89** [laughingman7743/PyAthena#238]
Hi everyone! I'm trying to run a `df.to_sql()` of a dataframe which has strings containing single quotes such as `bertop's` but I get the following error:

`DatabaseError: (pyathena.error.DatabaseError) An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:886: mismatched input 's'. Expecting: ')', ','`

I have tried escaping them with `''` but the error I get is:

`DatabaseError: (pyathena.error.DatabaseError) An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:885: mismatched input '\'. Expecting: ')', ','` 

Any ideas? 

Thank you very much in advance.

**Comment by laughingman7743** [comment]
Yes, it is true that if the value contains single quotes, an error will occur.
```
import pandas as pd
from urllib.parse import quote_plus
from sqlalchemy import create_engine

conn_str = "awsathena+rest://:@athena.{region_name}.amazonaws.com:443/" \
           "{schema_name}?s3_staging_dir={s3_staging_dir}&s3_dir={s3_dir}&compression=snappy"
engine = create_engine(conn_str.format(
    region_name="us-west-2",
    schema_name="default",
    s3_staging_dir=quote_plus("s3://BUCKET/tmp/"),
    s3_dir=quote_plus("s3://BUCKET/default/test/")),
    echo=True
)
df = pd.DataFrame({"a": ["foo", "bar", "jim o'rourke"]})
df.to_sql("test", engine, schema="default", index=False, if_exists="replace", method="multi")
````
The helper methods in the pandas.util package seem to work fine.
```
import pandas as pd
from pyathena import connect
from pyathena.pandas.util import to_sql

conn = connect(s3_staging_dir="s3://BUCKET/tmp/",
               region_name="us-west-2")
df = pd.DataFrame({"a": ["foo", "bar", "jim o'rourke"]})
to_sql(df, "test", conn, "s3://BUCKET/default/test/",
       schema="default", index=False, if_exists="replace")
```
If the value contains single quotes, it will be automatically escaped.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/formatter.py#L62-L72
Is the escaping process insufficient?

**Comment by avibrazil** [comment]
This is broken and it fails with queries as simple as

`select * from table where x in ('a', 'b')`
