### ISSUE TITLE
query "show partitions {catalog}.{database}.{table}" give error

### ISSUE THREAD

**Issue by yduan-polo** [laughingman7743/PyAthena#243]
>>> query="show partitions AwsDataCatalog.futures.account"
>>> cursor.execute(query)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yduan/Library/Python/3.8/lib/python/site-packages/pyathena/util.py", line 37, in _wrapper
    return wrapped(*args, **kwargs)
  File "/Users/yduan/Library/Python/3.8/lib/python/site-packages/pyathena/cursor.py", line 108, in execute
    raise OperationalError(query_execution.state_change_reason)
pyathena.error.OperationalError: FAILED: ParseException line 1:38 missing EOF at '.' near 'futures'

But if catalog is not specified, it works

>>> query="show partitions futures.account"
>>> cursor.execute(query)
<pyathena.cursor.Cursor object at 0x7fcfb8468ac0>

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/issues/220
You should be able to specify the catalog with the argument `catalog_name` as shown below.
```
cursor = connect(s3_staging_dir="s3://YOUR_S3_BUCKET/path/to/",
                 region_name="YOUR_REGION",
                 catalog_name="AwsDatacatalog").cursor()
query="show partitions futures.account"
cursor.execute(query)
```
Please try it.

**Comment by yduan-polo** [comment]
That works! Thanks you!!
