### ISSUE TITLE
Connecting on Athena (cross account) with assume role to perform some actions

### ISSUE THREAD

**Issue by richardsonlima** [laughingman7743/PyAthena#245]
## What happens?
After taking a look at the documentation (https://pypi.org/project/pyathena/) I noticed that `aws_access_key_id+aws_secret_access_key+region_name`  could be used to connect on Athena but if we need to pass something like `assume_role` it doesn't have some option to be used to connect to Athena located in another account performing assume role. However, the question is, do we've some option to do that, or does it still needs to be developed? 

## Troubleshooting performed
Did some tshoots but received this error 
```bash 
ATHENA_CONNECTION_STRING.format(region=self.region_name), props
java.sql.java.sql.SQLException: java.sql.SQLException: [Simba][AthenaJDBC](100071) An error has been thrown from
 the AWS Athena client. Unable to verify/create output bucket xxxxxxxxxxxxxx-us-east-1 
[Execution ID not available]
```

**Comment by laughingman7743** [comment]
Please check the credentials section of the README.
https://github.com/laughingman7743/PyAthena#credentials

**Comment by richardsonlima** [comment]
Ty @laughingman7743

**Comment by laughingman7743** [comment]
Looking at the error, it seems to be a JDBC version error. The JDBC version can be found in this repository.
https://github.com/laughingman7743/PyAthenaJDBC
The usage is different. I do not recommend using the JDBC version for Python.

**Comment by laughingman7743** [comment]
If this problem is not solved, please reopen it.
