### ISSUE TITLE
Slow MSCK REPAIR TABLE in to_sql

### ISSUE THREAD

**Issue by Liam3851** [laughingman7743/PyAthena#246]
At the end of pyathena.pandas.util.to_sql, MSCK REPAIR TABLE is called. MSCK REPAIR TABLE is exceedingly slow. For a brand-new table with 22 partitions and two partitioning levels, it takes me about 5 minutes to run. For larger tables it is almost unusable. See https://athena.guide/articles/msck-repair-table/ for a possible explanation that seems plausible enough to me.

It seems to me that significant performance could be gained if pyathena instead used the known partitions from the pandas DataFrame, which are used to construct the folder structure, and used direct ALTER TABLE ADD PARTITIONS commands. As a sample, I was able to run the direct ALTER TABLE for the above table (22 partitions, 2 levels), without even knowing the partitions ex ante (and thus needing to list the folder myself in boto3), in 5.8 seconds. 

Are there any contributing guidelines? Happy to submit a PR if desired.

**Comment by laughingman7743** [comment]
Pull requests are welcome.
There are no specific guidelines, but you should write tests. You need to set up your tests in GitHubActions in the repository where you forked them. In addition, the unit tests require an AWS environment. You will need to prepare your own account. The AWS account used in this repository is my personal account and cannot be shared.

**Comment by laughingman7743** [comment]
Since we are creating a partition prefix here, it would be a good idea to generate a configuration that can be used to ALTER TABLE ADD PARTITION.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/pandas/util.py#L207-L209
I'll try to change the implementation from REPAIR TABLE in the near future.
