### ISSUE TITLE
boto3 session as argument to connect()

### ISSUE THREAD

**Issue by benkehoe** [laughingman7743/PyAthena#248]
Currently, you can provide arguments that are used to create a boto3 session, but you can't just provide your own session. That limits the ability, for example, to use [`aws_sso_lib.get_boto3_session()`](https://github.com/benkehoe/aws-sso-util/tree/master/lib#get_boto3_session) to allow a script that knows what account and AWS SSO role it should be using to do that directly, rather than relying on it being configured in a profile.

**Comment by laughingman7743** [comment]
Do you mean you want to pass the Session object that is created inside the connection as an argument from outside?
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L130

**Comment by benkehoe** [comment]
Yes, exactly that. If I pass a session in, set `self._session` to that and skip all the session-creation logic inside the constructor.

**Comment by laughingman7743** [comment]
It seems to be a good improvement. It looks easy to implement, so I'll try to implement it over the weekend.

**Comment by laughingman7743** [comment]
Supported by the following branches. Please check it out.
https://github.com/laughingman7743/PyAthena/pull/252

**Comment by benkehoe** [comment]
Awesome! I added one comment on type hints
