### ISSUE TITLE
Python 3.6.4 Pip install doesnt work (futures dependancy)

### ISSUE THREAD

**Issue by GAwadhwalAtlassian** [laughingman7743/PyAthena#25]
attempting 
`pip3 install pyathena`
results in an error 
`futures requires Python '>=2.6, <3' but the running Python is 3.6.4`
This is because one of the requirements is futures, but probably is not required for python 3.

A work around is to install an older version of futures first, then installing pyathena
pip3 install futures==3.1.1

**Comment by laughingman7743** [comment]
@GAwadhwalAtlassian 
I fixed this issue with the following pull request. Please check it.
https://github.com/laughingman7743/PyAthena/pull/26

Thanks,

**Comment by GAwadhwalAtlassian** [comment]
awesome work, thanks so much.
