### ISSUE TITLE
Cannot compile SQLAlchemy CREATE TABLE statements

### ISSUE THREAD

**Issue by cansjt** [laughingman7743/PyAthena#258]
Hi !

Trying to compile a CREATE TABLE DDL statement fails with the error:
```
    def post_create_table(self, table):
>       raw_connection = table.bind.raw_connection()
E       AttributeError: 'NoneType' object has no attribute 'raw_connection'

pyathena/sqlalchemy_athena.py:218: AttributeError
```

Test case to reproduce:
```python
from sqlalchemy import Column, Integer, MetaData, Table
from sqlalchemy.sql.ddl import CreateTable

from pyathena.sqlalchemy_athena import AthenaDialect


def test_create_table_with_int():
    # Given
    table = Table('table_name', MetaData(), Column('column_name', String))
    dialect = AthenaDialect()

    # When
   statement = CreateTable(table).compile(dialect=dialect)
    # Alternative syntax (ends-up running the above statement)
    # table.create(bind=engine)

    # Then
    assert statement  # ...
```
Discussing this with [SQLAlchemy author](https://groups.google.com/g/sqlalchemy/c/QB_dSHafMXg), it seems the problem originate from using the connection query parameters to pass properties that inherently belong to the table. Plus the fact that a table is not necessarily bound to a connection, when being compiled into a `CREATE TABLE` statement.

But this would be a breaking change: basically I think the ~`s3_prefix`~ `s3_dir` connection parameter should be deprecated and abandoned, and proper use of dialect kwargs implemented. Meaning a table should be defined with:

```python
table = Table('table_name',
              MetaData(),
              Column('column_name', String),
              awsathena_prefix='s3://bucket/optional/path/prefix')
```

We are interested in working on this. Actually already have started, we need to polish our changes before opening a PR. But would you accept such a change?

Thanks.

**Comment by cansjt** [comment]
Note: implementing dialect kwargs would also allow to expand specify other table options like: the storage formats, table properties, _etc._

We'd be happy to contribute in that domain.

**Comment by laughingman7743** [comment]
If the current behavior does not change significantly, then I can accept the change.
However, when the table is created using the to_sql method of the DataFrame, it should be necessary to get the required option values from the connection string. You should also consider the use case of using SQLAlchemy and Pandas DataFrame.

**Comment by cansjt** [comment]
I am guessing most changes would be located in the `generate_ddl()` (in the `pyathena.pandas.utils` module).

But then, looking at the impl., the changes might be independent as there is no SQLAlchemy involved there.
And looking at the 'to_sql()' function definition and implementation, it seems you have to explicitly pass a `location` argument anyway. Though, not using pandas, not sure where people generally fetch this information from.

And, the other way around, I don't see places where the SQLAlchemy impl. would use stuff from pandas (that would have been suprising).

I guess deprecating the use of the `s3_prefix` from connection parameters could be restricted to the SQLAlchemy use case.

**Comment by cansjt** [comment]
My bad, looking at [this example](https://github.com/laughingman7743/PyAthena#to-sql) in the README, there is a way to use SQLAlchemy with Pandas.

**Comment by cansjt** [comment]
FYI [opened an issue](https://github.com/pandas-dev/pandas/issues/45259) on pandas repository, has I don't see how the dialect will continue to work with SQLAlchemy 2.0.
