### ISSUE TITLE
Integer type mishandled in DDL statements 

### ISSUE THREAD

**Issue by cansjt** [laughingman7743/PyAthena#260]
Athena uses different names for the integer type depending on whether the statement is a DML or DDL one. In the former it uses the regular `INTEGER` name, but in DDL it uses the name `INT`.

Currently PyAthena does not distinguish DDL from DML statements, which produces syntax errors when emitting `CREATE TABLE` statements. 

Note that in other places (e.g. [`pyathena.pandas.utils`](https://github.com/laughingman7743/PyAthena/blob/master/pyathena/pandas/util.py#L92)) this has been correctly handled.

**Comment by laughingman7743** [comment]
[This test](https://github.com/laughingman7743/PyAthena/blob/v2.3.2/tests/test_sqlalchemy_athena.py#L458-L517) will generate the following DDL.
```
CREATE EXTERNAL TABLE to_sql_cf248842dfc04d669524981a81bd9882 (
	col_int INTEGER, 
	col_bigint BIGINT, 
	col_float DOUBLE, 
	col_double DOUBLE, 
	col_string STRING, 
	col_boolean BOOLEAN, 
	col_timestamp TIMESTAMP, 
	col_date DATE
)
STORED AS PARQUET
LOCATION 's3://bucket/path/to/'
```
The following table is actually created in Athena.
```
CREATE EXTERNAL TABLE `to_sql_cf248842dfc04d669524981a81bd9882`(
  `col_int` int, 
  `col_bigint` bigint, 
  `col_float` double, 
  `col_double` double, 
  `col_string` string, 
  `col_boolean` boolean, 
  `col_timestamp` timestamp, 
  `col_date` date)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://bucket/path/to/'
TBLPROPERTIES (
  'parquet.compress'='SNAPPY', 
  'transient_lastDdlTime'='1613916874')
```
Athena doesn't actually seem to handle the difference between INT and INTEGERS sensitively.

**Comment by laughingman7743** [comment]
Please close this issue.

**Comment by cansjt** [comment]
I am sorry but we did have syntax errors with the INTEGER type at some point.

Maybe it also depends on the storage format from some weird reason, or something else. I am looking into it with a colleague to provide an example. If we find out that we had it wrong and cannot reproduce the issue, we'll close the issue obviously. Just give us the day, please. Thanks.

**Comment by cansjt** [comment]
Here is a failing example:
```sql
CREATE EXTERNAL TABLE default.table (
    entity_id INTEGER
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION
  's3://jt-eu-west-1-dev-datalake-pyathena-testing-bucket/cansjt/database/entity/'
;
```
So it seem to related to the storage format. We implemented support for JSON (more generally the `ROW FORMAT` construct), that we'll contribute in a future PR.
Let's close #258, then will fix that one first.

**Comment by laughingman7743** [comment]
Oh, so some Serde may cause errors. This is a terrible specification. 😱

**Comment by cansjt** [comment]
Actually the above example is wrong. It fails not because of the integer type, but because of the names of the table: `default.*table*`. Rename it `default.tabula` and it works.

**Comment by cansjt** [comment]
Actually the above example is wrong. It fails not because of the integer type, but because of the names of the table: `default.*table*`. Rename it `default.tabula` and it works.

While investigating, I had the exact same error, not because of the above name issue, but because the table already existed!

Looks like this error may be raised for a number of reasons. No longer having the logs and exact context when we faced other occurrences of this error, makes it tough to say for sure, if the issue was related to the `INTEGER` type or not.

I guess will close this for now.

**Comment by cansjt** [comment]
For memory's sake: some DDL statements do not handle INTEGER, like:
```sql
ALTER TABLE default.some_table ADD COLUMNS (some_data INT);
```
This is not something that is yet implemented in PyAthena, but we have started implementing some Alembic support for it.
