### ISSUE TITLE
Length-less VARCHAR aren't supported in DDL statements

### ISSUE THREAD

**Issue by cansjt** [laughingman7743/PyAthena#266]
When one defines a table as follows:
```python
table = Table(
    "table_name",
    MetaData(),
    Column("c", String),
    schema=SCHEMA,
    awsathena_location="s3://bucket/prefix/table_name",
)
```
And then tries to add in to Athena's catalog with:
```python
table.create(bind=connection)
```
The operation will fail because Athena does not support creating columns of type VARCHAR without a maximum length.
```
FAILED: ParseException line 2:0 mismatched input ')' expecting ( near 'VARCHAR' in primitive type specification
```
Given Athena's not always very user-friendly error messages, maybe we could catch the problem before sending the query to Athena, providing users with a more helpful and actionable diagnostic.

**Comment by laughingman7743** [comment]
I think you should submit a request for improvement to AWS support, because AWS is a customer-oriented company and they will make improvements.
I don't think there is any need to handle this kind of error message in DB-API.
