### ISSUE TITLE
query with wildcard % results in error due to bad string substitution

### ISSUE THREAD

**Issue by duanyutong** [laughingman7743/PyAthena#275]
```
File /usr/local/lib/python3.8/dist-packages/pyathena/formatter.py:187, in DefaultParameterFormatter.format(self, operation, parameters)
    181     else:
    182         raise ProgrammingError(
    183             "Unsupported parameter "
    184             + "(Support for dict only): {0}".format(parameters)
    185         )
--> 187 return (operation % kwargs).strip() if kwargs is not None else operation.strip()

ValueError: unsupported format character ''' (0x27) at index 94
```

`formatter.py:187` uses obsolete `(operation % kwargs)` which fails if the `operation` is a query containing `%`, e.g.

```SQL
SELECT col from table WHERE col LIKE 'prefix%'
```

One solution is switching to `str.format()`.

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena#query-with-parameter
> if % character is contained in your query, it must be escaped with %% like the following:
>
> SELECT col_string FROM one_row_complex
> WHERE col_string = %(param)s OR col_string LIKE 'a%%'

**Comment by duanyutong** [comment]
Thanks for the link. I tested the suggested workaround and it works.

However, I do still suggest transitioning to modern string format methods. It's a headache to deal with for users, and you have to keep the workaround in the documentation and keep pointing it out to users who fail to read it in detail.

**Comment by laughingman7743** [comment]
Please check the specifications of the DB-API parameters.
https://www.python.org/dev/peps/pep-0249/#paramstyle
