### ISSUE TITLE
to_sql raise an error if a partition already exists

### ISSUE THREAD

**Issue by bajram-hushi** [laughingman7743/PyAthena#276]
when I add data with already existed partition an error is raised:
` ERROR - FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. AlreadyExistsException(message:Partition already exists.)` 

The issue here is on those two lines:
https://github.com/laughingman7743/PyAthena/blob/9e42752b0cc7145a87c3a743bb2634fe125adfa7/pyathena/pandas/util.py#L269-L270

I think i would be better to rewrite this query as following:
```sql
   ALTER TABLE `{schema}`.`{name}` 
   ADD IF NOT EXISTS PARTITION ({partition[0]}) LOCATION '{partition[1]}' 
```

**Comment by laughingman7743** [comment]
Thank you. I'll fix it soon.
