### ISSUE TITLE
Cancel aborted queries

### ISSUE THREAD

**Issue by memeplex** [laughingman7743/PyAthena#28]
After pressing Ctrl-C on `cur.execute` or `future.result` a `cur.cancel` should be sent to the server since athena is paid per query and there is no point in paying for the rest of an aborted query.

**Comment by laughingman7743** [comment]
Related:
https://github.com/laughingman7743/PyAthenaJDBC/issues/56

**Comment by laughingman7743** [comment]
I fixed this issue with the following pull request.
https://github.com/laughingman7743/PyAthena/pull/31
Please check it.

**Comment by memeplex** [comment]
I don't think this is enough since the interruption could be catched at
another part. A finally clause checking for the query execution state would
be a more robust alternative, although that can't be done at the _poll
level.

**Comment by memeplex** [comment]
I'm not sure this is a good idea but it can also be addressed as a context
manager. For example, on cursor destruction/closing/exiting all active
queries could be cancelled. Then it's the user duty to ensure the cursor is
properly closed, as it should be. Your approach is still the right one for
interactive usage, tough.

**Comment by laughingman7743** [comment]
This library is open source. If you have an idea, please make pull request. 👍
