### ISSUE TITLE
if as_pandas not in pyathena.util anymore how to create dataframe from querying Athena?

### ISSUE THREAD

**Issue by claranamedeiros** [laughingman7743/PyAthena#290]
I am trying to run this query: 

cursor = connect(s3_staging_dir,
                 region_name).cursor()

df = cursor.execute(QUERY).as_pandas()

and getting the error:
AttributeError: 'Cursor' object has no attribute 'as_pandas'

I read that as_pandas not in pyathena.util anymore, is there a replacement for it?

Cheers.

**Comment by claranamedeiros** [comment]
@@laughingman7743

**Comment by claranamedeiros** [comment]
@laughingman7743

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena#pandascursor
Please check the README.
