### ISSUE TITLE
No longer a SQLAlchemy column for the Partition

### ISSUE THREAD

**Issue by nananathanh** [laughingman7743/PyAthena#292]
Hey @laughingman7743,

Since upgrading 2.4-> 2.5, I have encountered a problem where I can no longer access the partition as a SQLAlchemy column anymore.

If I run the following code with PyAthena 2.4, my table returns all the columns including the partition. Running with PyAthena 2.5, I get all the columns except the partition.

```python
import sqlalchemy as sa
from sqlalchemy.sql.schema import Table, MetaData

staging_bucket = "..."
athena_endpoint = "..."
db_name = "..." 
table_name = "..."

engine = sa.create_engine(
            f"{athena_endpoint}/{db_name}?s3_staging_dir=s3://{staging_bucket}",
            echo=True,
            future=False,
)
with engine.connect() as connection:
    table = Table(table_name, MetaData(), autoload_with=connection)
    for column in table.columns:
        print(column)
```

Note: My Database & Table already exists in AWS Glue - I am trying to run read only statements

As a side note, with `echo=True`, I don't get any executed statement in the logs with 2.5.
With 2.4, I see the following query is generated:

```SQL
SELECT
                  table_schema,
                  table_name,
                  column_name,
                  data_type,
                  is_nullable,
                  column_default,
                  ordinal_position,
                  comment
                FROM information_schema.columns
                WHERE table_schema = '...'
                AND table_name = '...'
```

**Comment by laughingman7743** [comment]
It seems that the change in metadata retrieval from the information schema to via API may have had an impact.
https://github.com/laughingman7743/PyAthena/pull/286/files
I will need to look more closely at the impact of this change on the partitioning table.

**Comment by laughingman7743** [comment]
Sorry, I was missing the addition of the partition key columns in sqlalchemy's get_columns method. Fixed in the following branch.
https://github.com/laughingman7743/PyAthena/pull/293
I will merge and release a new version v2.5.2 after the test passes.
