### ISSUE TITLE
Deprecation Warning about re.compile in model.py/AthenaRowFormatSerde

### ISSUE THREAD

**Issue by sadikkuzu** [laughingman7743/PyAthena#315]
Hi,

I'm using pyathena 2.6.1 and in my tests I get such warning:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/23168063/167317559-dfd7e8a5-c894-4060-8d55-dd22c9a2efd9.png">

Is this about https://bugs.python.org/issue22493 (https://github.com/python/cpython/issues/66683)?

**Comment by laughingman7743** [comment]
Thanks, it will be fixed in the next version.
https://github.com/laughingman7743/PyAthena/pull/316
