### ISSUE TITLE
Type code contract broken

### ISSUE THREAD

**Issue by memeplex** [laughingman7743/PyAthena#32]
The DBAPI specifies that

> The type_code must compare equal to one of Type Objects defined below

https://www.python.org/dev/peps/pep-0249/#type-objects-and-constructors

But I think there is a case problem here because the description in the cursor contains strings like `integer` but `NUMBER` is defined as:

```
 NUMBER = DBAPITypeObject('BOOLEAN', 'TINYINT', 'SMALLINT', 'BIGINT', 'INTEGER', 
                          'REAL', 'DOUBLE', 'FLOAT', 'DECIMAL', 'NUMERIC')   
```

so it doesn't compare equal to the value in the description.

**Comment by memeplex** [comment]
Also `__cmp__` doesn't work in python 3 anymore.

**Comment by memeplex** [comment]
Looks fine to me.

**Comment by laughingman7743** [comment]
Thanks,
