### ISSUE TITLE
pyathena.connect does not accept `aws_access_key_id` as a keyword argument

### ISSUE THREAD

**Issue by shumingpeh** [laughingman7743/PyAthena#327]
We recently upgraded to `2.9.0` and ran into this issue, when we tried to initialise an athena connection through `pyathena.connect`. snippet of how we connect:

```
import pyathena
from pyathena import connect
from pyathena.pandas.cursor import PandasCursor

connection = connect(
    s3_staging_dir=f"{settings.S3_ATHENA_QUERY_DIRECTORY}query_{today_date}",
    region_name=settings.AWS_DEFAULT_REGION,
    aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
    aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"],
    cursor_class=PandasCursor,
)
```

this throws an error of `pyathena.error.OperationalError: __init__() got an unexpected keyword argument 'aws_access_key_id'`

**Comment by laughingman7743** [comment]
Thanks. Fixed in the following branch.
https://github.com/laughingman7743/PyAthena/pull/328
I will merge and release 2.9.1.
