### ISSUE TITLE
how to "describe a query" using pyathena connector

### ISSUE THREAD

**Issue by ni-todo-spot** [laughingman7743/PyAthena#338]
Hey all!

I've been using this connector for a project involving other dpapi2 connectors.

As part of the project I'd like "describe a query" or in other words - supply a raw string sql statement and get for it the columns names and their respective data types, without actually executing the query.

other types of connectors / sdks supply such an option:
https://docs.snowflake.com/en/user-guide/python-connector-api.html#describe
https://docs.databricks.com/sql/language-manual/sql-ref-syntax-aux-describe-query.html

Reading the docs of this project I saw the `AthenaResultSet` class which seems to be what I need but it seems the query needs to be executed in order for me to be able to use it.

Is there some kind of feature which allows me the mentioned above?

Many Thanks!

**Comment by laughingman7743** [comment]
https://docs.aws.amazon.com/athena/latest/ug/describe-table.html
https://docs.aws.amazon.com/athena/latest/ug/describe-view.html
I don't think Athena supports describe of query results. It may be possible to run a query with LIMIT 0 to not get the result, and get the result information from `cursor.description`.

**Comment by laughingman7743** [comment]
Athena is supposed to charge based on the amount of scans, so you probably don't need to worry about the cost.
If you are concerned, you should certainly contact AWS support.
