### ISSUE TITLE
init() got an unexpected keyword argument profile

### ISSUE THREAD

**Issue by nikhil27472** [laughingman7743/PyAthena#340]
Hi,
I'm regularly using pyathena but I'm getting the issue with the **version from 2.9.2.**

```
from pyathena import connect
from pyathena.pandas_cursor import PandasCursor
from pyathena.converter import Converter

cur = connect(s3_staging_dir='<staging_directory_url>',
                region_name='<aws_region>',
                cursor_class = PandasCursor,
                converter=CustomPandasTypeConverter(),
                work_group = '<workgroup_name>').cursor()

query = 'SELECT * FROM <schema>.<table>'
df = cur.execute(query).as_pandas()
```

This is giving an error 
```
**OperationalError:** __init()__ got an unexpected keyword argument _'profile'_
```

In the previous version i was able to run the same query but why not in present version. Please Help.

**Comment by laughingman7743** [comment]
It does not occur in my environment. Is it occurring from 2.9.3, which includes this change?
https://github.com/laughingman7743/PyAthena/pull/332/files
Maybe it has something to do with the s3fs version. The version of s3fs in my environment is `s3fs==2022.5.0`.

**Comment by nikhil27472** [comment]
Thanks, Its working fine for me after updating the s3fs.
