### ISSUE TITLE
PyArrow Requirement Exceeds Lambda Unzipped Max

### ISSUE THREAD

**Issue by aaronclong** [laughingman7743/PyAthena#341]
The `PandasCursor` is no longer usable in **AWS Lambdas** because of the requirement to use [PyArrow](https://pypi.org/project/pyarrow/). The library is quite large, and it exceeds [AWS Unzipped file size limit](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html). It is prevent deploys at the moment. 

PyArrow is quite large, and other libraries have run into similar issues: https://github.com/snowflakedb/snowflake-connector-python/issues/213

I wonder if could be made an optional dependency for the `PandasCursor`? The library could use the older logic as fallback for when it isn't present.

![image](https://user-images.githubusercontent.com/7354981/176472061-6bd71314-358f-4560-9f0d-6ed5ba592170.png)

**Comment by aaronclong** [comment]
To be fair, am looking at other libraries to trim here. However, `PyArrow` is the largest, and it wasn't required until a recent update.

**Comment by laughingman7743** [comment]
PyArraow is required by the implementation of the unloading option added in v2.9.0, so it has been added to the PandasCursor dependency.
https://github.com/laughingman7743/PyAthena/releases/tag/v2.9.0

Since Pandas has the option to read Parquet files using PyArrow or FastParquet, it may be possible to specify a fallback to FastParquet if PyArrow is not available. Then the PyArraow dependency may not be required.
https://pandas.pydata.org/docs/reference/api/pandas.read_parquet.html
https://github.com/dask/fastparquet
https://pypi.org/project/fastparquet/

**Comment by aaronclong** [comment]
@laughingman7743  thanks for getting back to this so quickly, do appreciate that.
I didn't know about the unload, this is interesting.

It would be awesome if this was a config to be set on the cursor construction. The default would just assume it to be CSV. 

I know you need to balance multiple use cases here, but I don't think unload is the most common use case of this. However, I guess I could just fork the logic of the legacy `PandasCursor` and wrap that in a separate library.

**Comment by aaronclong** [comment]
@laughingman7743  thank you for looking into this! Will do! Let me know if you need help.

**Comment by aaronclong** [comment]
@laughingman7743  thank you so much for doing this!!! I really do appreciate it.

However, I did run into one more problem haha. The strict botocore version of aiobotocore that s3fs imports is quite difficult to trace. I opened up an issue on their github to see if anything could be done to ease this. I doubtful there is because of the complexity of botocore main. https://github.com/aio-libs/aiobotocore/issues/957 

I noticed other people have opened similar issues on here as well: https://github.com/laughingman7743/PyAthena/issues/345.

I am wondering in terms of this project whether an interface could be made to limit this restrictive behavior. Essentially a baseclass/interface with set methods that could be used internally. The default would s3fs to power this, but if we don't want the restrictiveness of the botocore of s3fs, we could implement the interface ourselves.

It would better safeguard this library from [s3fs](https://github.com/fsspec/s3fs), and allow users to override behaviors based on their needs. It doesn't look like it would be terribly hard to do.

- https://github.com/laughingman7743/PyAthena/blob/e236227f5e8973f35d43246929ac48e9b9964896/pyathena/pandas/result_set.py#L308
- https://github.com/laughingman7743/PyAthena/blob/e236227f5e8973f35d43246929ac48e9b9964896/pyathena/pandas/result_set.py#L292

**Comment by aaronclong** [comment]
@laughingman7743  admittedly, it shouldn't be your concern, two libraries removed. Why I am thinking of using Interface design to shield you, other user, and myself from this issue.

like:
```
class FileSystemIface(ABC):
  @abstractmethod
  def fs(self, f: str):
    pass
  ....
```

**Comment by aaronclong** [comment]
> @laughingman7743 admittedly, it shouldn't be your concern, two libraries removed. Why I am thinking of using Interface design to shield you, other user, and myself from this issue.
> 
> like:
> 
> ```
> class FileSystemIface(ABC):
>   @abstractmethod
>   def fs(self, f: str):
>     pass
>   ....
> 
> 
> with athena_conn.cursor(PandasCursor, unload=True, fs: FileSystemIface=DefaultFs) as stuff:
>   pass
> ```

@laughingman7743  do you have any thoughts on this proposal?

**Comment by laughingman7743** [comment]
I do not believe that introducing such an interface will solve this problem, nor do I intend to.
I think the best solution is to make sure that the boto3 and botocore versions specify dependencies higher than the version that supports the resolve_checksum_context.

**Comment by laughingman7743** [comment]
There was a similar boto3 and botocore issue recently, and I think the same handling is best.
https://github.com/laughingman7743/PyAthena/issues/336
https://github.com/laughingman7743/PyAthena/pull/337

**Comment by aaronclong** [comment]
> I do not believe that introducing such an interface will solve this problem, nor do I intend to. I think the best solution is to make sure that the boto3 and botocore versions specify dependencies higher than the version that supports the resolve_checksum_context.

@laughingman7743 currently there is only one version of botocore that you will have to force pin
