### ISSUE TITLE
Installing pyathena[pandas]==2.9.6

### ISSUE THREAD

**Issue by dblado** [laughingman7743/PyAthena#345]
Possibly not the right place to ask this question, but I couldn't find an answer anywhere else.

In a fresh virtual environment, pip install pyathena[pandas]==2.9.6 has to check so many versions of packages (especially boto*). Is there a reason why the constraints are not more strict?

$ pip install pyathena[pandas]
Collecting pyathena[pandas]
  Using cached PyAthena-2.9.6-py3-none-any.whl (56 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.29-py3-none-any.whl (9.0 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.29-py3-none-any.whl (132 kB)
Collecting tenacity>=4.1.0
  Using cached tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting pandas>=1.3.0
  Using cached pandas-1.4.3-cp39-cp39-macosx_10_9_x86_64.whl (11.5 MB)
Collecting pyarrow>=7.0.0
  Using cached pyarrow-8.0.0-cp39-cp39-macosx_10_13_x86_64.whl (22.4 MB)
Collecting s3fs>=2021.09.0
  Using cached s3fs-2022.5.0-py3-none-any.whl (27 kB)
Collecting jmespath<2.0.0,>=0.7.1
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting s3transfer<0.7.0,>=0.6.0
  Using cached s3transfer-0.6.0-py3-none-any.whl (79 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting urllib3<1.27,>=1.25.4
  Using cached urllib3-1.26.10-py2.py3-none-any.whl (139 kB)
Collecting pytz>=2020.1
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting numpy>=1.18.5
  Using cached numpy-1.23.1-cp39-cp39-macosx_10_9_x86_64.whl (18.1 MB)
Collecting aiobotocore~=2.3.0
  Using cached aiobotocore-2.3.4-py3-none-any.whl (64 kB)
Collecting aiohttp<=4
  Using cached aiohttp-3.8.1-cp39-cp39-macosx_10_9_x86_64.whl (574 kB)
Collecting fsspec==2022.5.0
  Using cached fsspec-2022.5.0-py3-none-any.whl (140 kB)
Collecting aioitertools>=0.5.1
  Using cached aioitertools-0.10.0-py3-none-any.whl (23 kB)
Collecting aiobotocore~=2.3.0
  Using cached aiobotocore-2.3.3.tar.gz (65 kB)
  Preparing metadata (setup.py) ... done
  Using cached aiobotocore-2.3.2.tar.gz (104 kB)
  Preparing metadata (setup.py) ... done
  Using cached aiobotocore-2.3.1.tar.gz (65 kB)
  Preparing metadata (setup.py) ... done
  Using cached aiobotocore-2.3.0.tar.gz (65 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of pyathena to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of tenacity to determine which version is compatible with other requirements. This could take a while.
Collecting tenacity>=4.1.0
  Using cached tenacity-8.0.0-py3-none-any.whl (22 kB)
INFO: pip is looking at multiple versions of fsspec to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of s3fs to determine which version is compatible with other requirements. This could take a while.
Collecting s3fs>=2021.09.0
  Using cached s3fs-2022.3.0-py3-none-any.whl (26 kB)
Collecting fsspec==2022.3.0
  Using cached fsspec-2022.3.0-py3-none-any.whl (136 kB)
Collecting aiobotocore~=2.2.0
  Using cached aiobotocore-2.2.0-py3-none-any.whl
Collecting s3fs>=2021.09.0
  Using cached s3fs-2022.2.0-py3-none-any.whl (26 kB)
Collecting aiobotocore~=2.1.0
  Using cached aiobotocore-2.1.2.tar.gz (58 kB)
  Preparing metadata (setup.py) ... done
Collecting fsspec==2022.02.0
  Using cached fsspec-2022.2.0-py3-none-any.whl (134 kB)
Collecting aiobotocore~=2.1.0
  Using cached aiobotocore-2.1.1.tar.gz (57 kB)
  Preparing metadata (setup.py) ... done
  Using cached aiobotocore-2.1.0.tar.gz (54 kB)
  Preparing metadata (setup.py) ... done
Collecting s3fs>=2021.09.0
  Using cached s3fs-2022.1.0-py3-none-any.whl (25 kB)
Collecting fsspec==2022.01.0
  Using cached fsspec-2022.1.0-py3-none-any.whl (133 kB)
Collecting s3fs>=2021.09.0
  Using cached s3fs-2021.11.1-py3-none-any.whl (25 kB)
Collecting fsspec==2021.11.1
  Using cached fsspec-2021.11.1-py3-none-any.whl (132 kB)
Collecting aiobotocore~=2.0.1
  Using cached aiobotocore-2.0.1.tar.gz (54 kB)
  Preparing metadata (setup.py) ... done
Collecting s3fs>=2021.09.0
  Using cached s3fs-2021.11.0-py3-none-any.whl (25 kB)
Collecting fsspec==2021.11.0
  Using cached fsspec-2021.11.0-py3-none-any.whl (132 kB)
Collecting aiobotocore~=1.4.1
  Using cached aiobotocore-1.4.2.tar.gz (52 kB)
  Preparing metadata (setup.py) ... done
  Using cached aiobotocore-1.4.1.tar.gz (52 kB)
  Preparing metadata (setup.py) ... done
Collecting s3fs>=2021.09.0
  Using cached s3fs-2021.10.1-py3-none-any.whl (26 kB)
Collecting fsspec==2021.10.1
  Using cached fsspec-2021.10.1-py3-none-any.whl (125 kB)
Collecting s3fs>=2021.09.0
  Using cached s3fs-2021.10.0-py3-none-any.whl (26 kB)
Collecting fsspec==2021.10.0
  Using cached fsspec-2021.10.0-py3-none-any.whl (125 kB)
INFO: pip is looking at multiple versions of fsspec to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of s3fs to determine which version is compatible with other requirements. This could take a while.
Collecting s3fs>=2021.09.0
  Using cached s3fs-2021.9.0-py3-none-any.whl (26 kB)
Collecting fsspec==2021.09.0
  Using cached fsspec-2021.9.0-py3-none-any.whl (123 kB)
INFO: pip is looking at multiple versions of pyarrow to determine which version is compatible with other requirements. This could take a while.
Collecting pyarrow>=7.0.0
  Using cached pyarrow-7.0.0-cp39-cp39-macosx_10_13_x86_64.whl (20.2 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
Collecting pandas>=1.3.0
  Using cached pandas-1.4.2-cp39-cp39-macosx_10_9_x86_64.whl (11.1 MB)
  Using cached pandas-1.4.1-cp39-cp39-macosx_10_9_x86_64.whl (11.5 MB)
  Using cached pandas-1.4.0-cp39-cp39-macosx_10_9_x86_64.whl (11.5 MB)
INFO: pip is looking at multiple versions of pyarrow to determine which version is compatible with other requirements. This could take a while.
  Using cached pandas-1.3.5-cp39-cp39-macosx_10_9_x86_64.whl (11.3 MB)
  Using cached pandas-1.3.4-cp39-cp39-macosx_10_9_x86_64.whl (11.6 MB)
  Using cached pandas-1.3.3-cp39-cp39-macosx_10_9_x86_64.whl (11.6 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached pandas-1.3.2-cp39-cp39-macosx_10_9_x86_64.whl (11.6 MB)
INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
  Using cached pandas-1.3.1-cp39-cp39-macosx_10_9_x86_64.whl (11.3 MB)
  Using cached pandas-1.3.0-cp39-cp39-macosx_10_9_x86_64.whl (11.6 MB)
INFO: pip is looking at multiple versions of botocore to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of boto3 to determine which version is compatible with other requirements. This could take a while.
Collecting boto3>=1.13.20
  Using cached boto3-1.24.28-py3-none-any.whl (132 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting botocore>=1.16.20
  Using cached botocore-1.27.28-py3-none-any.whl (9.0 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.27-py3-none-any.whl (132 kB)
INFO: pip is looking at multiple versions of pyathena to determine which version is compatible with other requirements. This could take a while.
Collecting botocore>=1.16.20
  Using cached botocore-1.27.27-py3-none-any.whl (9.0 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.26-py3-none-any.whl (132 kB)
INFO: pip is looking at multiple versions of botocore to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting botocore>=1.16.20
  Using cached botocore-1.27.26-py3-none-any.whl (9.0 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.25-py3-none-any.whl (132 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting botocore>=1.16.20
  Using cached botocore-1.27.25-py3-none-any.whl (9.0 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.24-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.24-py3-none-any.whl (9.0 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.23-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.23-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.22-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.22-py3-none-any.whl (8.9 MB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of boto3 to determine which version is compatible with other requirements. This could take a while.
Collecting boto3>=1.13.20
  Using cached boto3-1.24.21-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.21-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.20-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.20-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.19-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.19-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.18-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.18-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.17-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.17-py3-none-any.whl (8.9 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting boto3>=1.13.20
  Using cached boto3-1.24.16-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.16-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.15-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.15-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.14-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.14-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.13-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.13-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.12-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.12-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.11-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.11-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.10-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.10-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.9-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.9-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.8-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.8-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.7-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.7-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.6-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.6-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.5-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.5-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.4-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.4-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.3-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.3-py3-none-any.whl (8.9 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.2-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.2-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.1-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.1-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.24.0-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.27.0-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.10-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.10-py3-none-any.whl (8.8 MB)
Collecting s3transfer<0.6.0,>=0.5.0
  Using cached s3transfer-0.5.2-py3-none-any.whl (79 kB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.9-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.9-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.8-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.8-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.7-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.7-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.6-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.6-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.5-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.5-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.4-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.4-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.3-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.3-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.2-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.2-py3-none-any.whl (8.8 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.1-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.1-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.23.0-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.26.0-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.13-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.13-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.12-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.12-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.11-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.11-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.10-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.10-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.9-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.9-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.8-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.8-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.7-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.7-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.6-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.6-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.5-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.5-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.4-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.4-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.3-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.3-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.2-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.2-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.1-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.1-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.22.0-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.25.0-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.46-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.46-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.45-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.45-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.44-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.44-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.43-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.43-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.42-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.42-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.41-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.41-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.40-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.40-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.39-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.39-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.38-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.38-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.37-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.37-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.36-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.36-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.35-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.35-py3-none-any.whl (8.7 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.34-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.34-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.33-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.33-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.32-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.32-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.31-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.31-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.30-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.30-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.29-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.29-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.28-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.28-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.27-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.27-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.26-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.26-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.25-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.25-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.24-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.24-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.23-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.23-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.22-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.22-py3-none-any.whl (8.6 MB)
Collecting boto3>=1.13.20
  Using cached boto3-1.21.21-py3-none-any.whl (132 kB)
Collecting botocore>=1.16.20
  Using cached botocore-1.24.21-py3-none-any.whl (8.6 MB)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/wrapt/
Collecting wrapt>=1.10.10
  Using cached wrapt-1.14.1-cp39-cp39-macosx_10_9_x86_64.whl (35 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.7.2-cp39-cp39-macosx_10_9_x86_64.whl (121 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.0-cp39-cp39-macosx_10_9_x86_64.whl (36 kB)
Collecting attrs>=17.3.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting charset-normalizer<3.0,>=2.0
  Using cached charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.2-cp39-cp39-macosx_10_9_x86_64.whl (28 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting typing_extensions>=4.0
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting idna>=2.0
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Installing collected packages: pytz, wrapt, urllib3, typing_extensions, tenacity, six, numpy, multidict, jmespath, idna, fsspec, frozenlist, charset-normalizer, attrs, async-timeout, yarl, python-dateutil, pyarrow, aiosignal, aioitertools, pandas, botocore, aiohttp, s3transfer, aiobotocore, s3fs, boto3, pyathena
Successfully installed aiobotocore-2.3.4 aiohttp-3.8.1 aioitertools-0.10.0 aiosignal-1.2.0 async-timeout-4.0.2 attrs-21.4.0 boto3-1.24.29 botocore-1.27.29 charset-normalizer-2.1.0 frozenlist-1.3.0 fsspec-2022.5.0 idna-3.3 jmespath-1.0.1 multidict-6.0.2 numpy-1.23.1 pandas-1.4.3 pyarrow-8.0.0 pyathena-2.9.6 python-dateutil-2.8.2 pytz-2022.1 s3fs-2022.5.0 s3transfer-0.6.0 six-1.16.0 tenacity-8.0.1 typing_extensions-4.3.0 urllib3-1.26.10 wrapt-1.14.1 yarl-1.7.2

**Comment by laughingman7743** [comment]
This is probably because of the strict specification of the botocore dependency of aiobotocore on which s3fs depends.
https://github.com/fsspec/s3fs/blob/main/requirements.txt#L1
https://github.com/aio-libs/aiobotocore/blob/master/setup.py#L10
PyAthena does not require such a strict version specification, so I don't specify it, and the Pandas package on which s3fs depends is an extra package.
