### ISSUE TITLE
Can't cast to VARBINARY

### ISSUE THREAD

**Issue by takacsd** [laughingman7743/PyAthena#361]
Hi,

first of all: great project.

I already created quite complex queries and everything works great, but it seems like there is a problem with the `VARBINARY` type mapping.
If I try to `cast` a column to `VARBINARY`, the generated SQL looks like this:
```
CAST("colname" AS BINARY)
```
I get `OperationalError: SYNTAX_ERROR: line 11:56: Unknown type: binary` exception.
And according to the [documentation](https://prestodb.io/docs/current/language/types.html#varbinary) there is no `BINARY` type, only `VARBINARY`.

If I just blindly change
https://github.com/laughingman7743/PyAthena/blob/4f4971cbb64bb4d3c7b775e3c4800b11e7f65ece/pyathena/sqlalchemy_athena.py#L433
to
```
        return "VARBINARY"
```
It seems to work.

I don't know if this change has other effect, so I'm not comfortable to create a PR...

**Comment by laughingman7743** [comment]
If you change it to VARBINARY, you get the following error when creating the table.
```
sqlalchemy.exc.OperationalError: (pyathena.error.OperationalError) FAILED: ParseException line 1:75 cannot recognize input near 'VARBINARY' ')' 'STORED' in column type
[SQL: 
CREATE EXTERNAL TABLE `default`.test_binary (
	column1 VARCHAR(10),
	column2 VARBINARY
)
STORED AS PARQUET
LOCATION 's3://bucket/path/to/'
TBLPROPERTIES (
	'orc.compress' = 'SNAPPY'
)
]
```
You can check it with the following simple code.
```
from sqlalchemy import types, create_engine, Table, MetaData, Column

conn_str = (
    "awsathena+rest://:@athena.{region_name}.amazonaws.com:443/"
    "{schema_name}?s3_staging_dir={s3_staging_dir}"
)
engine = create_engine(
    conn_str.format(
        region_name="us-west-2",
        schema_name="default",
        s3_staging_dir="s3://bucket/path/to/"
    ),
    echo=True,
)

table = Table(
    "test_binary",
    MetaData(schema="default"),
    Column("column1", types.String(10)),
    Column("column2", types.BINARY),
    awsathena_location=f"s3://bucket/path/to/",
    awsathena_file_format="PARQUET",
    awsathena_tblproperties={
        "orc.compress": "SNAPPY",
    }
)
table.create(bind=engine)
```
I think this problem occurs because Athena uses Hive for DDL and Presto for DML. It would be better to convert the BINARY type to VARBINARY at CAST in the following place.
https://github.com/laughingman7743/PyAthena/blob/4f4971cbb64bb4d3c7b775e3c4800b11e7f65ece/pyathena/sqlalchemy_athena.py#L337-L344

**Comment by laughingman7743** [comment]
I fixed it in the following branch. Please check it.
https://github.com/laughingman7743/PyAthena/pull/362

**Comment by takacsd** [comment]
If I do `cast(col, BINARY)` it gets converted to `CAST("colname" AS VARBINARY)` and is working fine.
but if I do `cast(col, VARBINARY)` it gets converted to `CAST("colname" AS BINARY)` which is kind of weird, and is obviously not working.
So instead of this:
https://github.com/laughingman7743/PyAthena/pull/362/commits/f34de8f64720f26141d678db9efa51709697e19c#diff-0cc6c6cef67adf7b211eccc2704d5a9d298a4303d474e5fa10a83fcc49c4447eR342
I would go either
```py
        elif isinstance(cast.type, types.VARBINARY):
```
because that was the type I tried first based on the Athena/Presto documentation,
or
```py
        elif isinstance(cast.type, (types.BINARY, types.VARBINARY)):
```
so everything is covered.

**Comment by laughingman7743** [comment]
OK, I'll add VARBINARY too.

**Comment by laughingman7743** [comment]
I will merge it once the test passes and will release the new version soon. Thanks.

**Comment by takacsd** [comment]
Perfect, thanks for the quick response!
