### ISSUE TITLE
Casting floats uses FLOAT instead of REAL

### ISSUE THREAD

**Issue by ticowiko** [laughingman7743/PyAthena#368]
The pyathena client transforms requests to cast to `Float` using the `FLOAT` type, instead of the `REAL` type. This leads to a broken conversion (the query will simply fail). `FLOAT` should be used in DDL statements, but not `SELECT` statements. From the Athena docs :

```In Athena, use float in DDL statements like CREATE TABLE and real in SQL functions like SELECT CAST.```

**Comment by laughingman7743** [comment]
https://docs.aws.amazon.com/athena/latest/ug/data-types.html
> float – A 32-bit signed single-precision floating point number. The range is 1.40129846432481707e-45 to 3.40282346638528860e+38, positive or negative. float follows the IEEE Standard for Floating-Point Arithmetic (IEEE 754). Equivalent to the real in Presto. In Athena, use float in DDL statements like CREATE TABLE and real in SQL functions like SELECT CAST. The AWS Glue crawler returns values in float, and Athena translates real and float types internally (see the [June 5, 2018](https://docs.aws.amazon.com/athena/latest/ug/release-notes.html#release-note-2018-06-05) release notes).

**Comment by laughingman7743** [comment]
If an error has occurred, please share the code to reproduce and the stack trace.
