### ISSUE TITLE
Using structured fields with PyAthena

### ISSUE THREAD

**Issue by HenriqueMAlmeida** [laughingman7743/PyAthena#371]
I'm trying to query a table that has columns with struct fields in the following format:

`{quantity=1, price=0.1, valid_data=2022-xx-xx 08:42:10.2431}`

I can execute simple queries using the sub-fields inside these structures, but I would like to use ORM.
However, I can't seem to find a way to map struct fields and these seem to be simply interpreted as a string  "{quantity... }"

Is there currently a way to use PyAthena along with SQLAlchemy ORM to map these fields?

Thanks!

**Comment by laughingman7743** [comment]
Currently, struct type is not supported.
Maybe python-bigquery-sqlalchemy's handling of the STRUCT type would be helpful for implementation.
https://github.com/googleapis/python-bigquery-sqlalchemy/blob/main/sqlalchemy_bigquery/_struct.py#L46

**Comment by HenriqueMAlmeida** [comment]
Thank you, I'll have a look!

**Comment by HenriqueMAlmeida** [comment]
I've tried to use the STRUCT type directly from BigQuery and I get the following error:

`sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.StrSQLCompiler object at 0x7fd91da5ea00> can't render element of type <function struct_getitem_op at 0x7fd91df84280> (Background on this error at: https://sqlalche.me/e/14/l7de)`

I know this is a bit out of the scope of PyAthena, but is there any tip you can give me on what I am missing to integrate this as a custom type?

**Comment by laughingman7743** [comment]
You can register an issue in the python-bigquery-sqlalchemy repository.
https://github.com/googleapis/python-bigquery-sqlalchemy/issues

**Comment by HenriqueMAlmeida** [comment]
Ok, thank you
