### ISSUE TITLE
Support for cross-account / cross region queries (glue )

### ISSUE THREAD

**Issue by asifkazi** [laughingman7743/PyAthena#374]
Need the ability to support cross-account, cross-region queries. The Athena API itself supports it: https://docs.aws.amazon.com/athena/latest/ug/security-iam-cross-account-glue-catalog-access.html

None of the applications which depend on pyathena can support cross account glue/athena access until pyathena supports it

e.g. Redash, Superset, Preset etc.

Surprised this hasn't come up before

**Comment by laughingman7743** [comment]
Is there something special I need to implement to use this feature? The documentation seems to describe how to add permissions and catalogs, but I can't find anything that would require any special implementation.

**Comment by asifkazi** [comment]
There is no way to pass the catalog name  which is an accounted. I don't see anything in the connection string or the config params which will allow me to specify cross account, cross region catalog

**Comment by laughingman7743** [comment]
Is that different from the argument `catalog_name` that can be specified in the connection object?
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L50
