### ISSUE TITLE
Support for VACUUM - Iceberg

### ISSUE THREAD

**Issue by nicor88** [laughingman7743/PyAthena#382]
# What
With the introduction of Iceberg a new vacuum operation was added, but when trying to run with pyathena I run in this issue:

```
pyathena.error.DatabaseError: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:1: mismatched input 'VACUUM'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'PREPARE', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'UNLOAD', 'UPDATE', 'USE', <query>
```

**Comment by nicor88** [comment]
The issue seems related to the underlying boto3 libraries

**Comment by nicor88** [comment]
```
import boto3

client = boto3.client('athena')


response = client.start_query_execution(
    QueryString='VACCUM silver.iceberg_increment',
    WorkGroup='athena_v3',
)
```
This snippet of code lead to the same issue above. @laughingman7743 we might need to approach the maintainers of boto3.

**Comment by nicor88** [comment]
Nevermind, this is not an issue, the keywoard that I used is wrong, should be `VACUUM`

**Comment by nicor88** [comment]
I need to re-open this, as even if using `VACUUM` I still get the same error.

**Comment by laughingman7743** [comment]
https://docs.aws.amazon.com/athena/latest/ug/vacuum-statement.html
> VACUUM is transactional and is supported only for Apache Iceberg tables in Athena engine version 3.

The VACUUM statement seems to be supported since `Athena engine version 3`. Please check if `Athena engine version 3` is set in your workgroup configuration. You may also need to make sure that your Boto3 version is up-to-date. In that case, you can try `pip install -U boto3` to update the version of boto3.

**Comment by laughingman7743** [comment]
This library only calls the boto3 API. If an error occurs, there is nothing this library can do about it; you should be able to register the issue with AWS support or boto3.

**Comment by nicor88** [comment]
@laughingman7743 I'm using an explicit workgroup with `v3`, and then I'm using the latest boto3 apis. Somehow
If I run this
```
import boto3

client = boto3.client('athena')


response = client.start_query_execution(
    QueryString='VACCUM silver.iceberg_increment',
    WorkGroup='athena_v3',
)
```
all works,
same if I run this

```
cursor = connect(
    work_group='athena_v3',
    s3_staging_dir="s3://tmp-datalake-dev-901621332207-eu-central-1/py_athena/",).cursor()
data = cursor.execute("vacuum silver.iceberg_increment")
print(cursor)
```

Most likely might be on dbt-athena, but still didn't find the issue...as it uses cursor.execute as specified above and works.

**Comment by laughingman7743** [comment]
I see. I'll look into it this weekend.

**Comment by nicor88** [comment]
@laughingman7743 it's super hood, really.

**Comment by nicor88** [comment]
@laughingman7743 for full disclosure, I tried to upgrade to latest pyathena (2.15) version and latest boto3 version (1.26.16),and botocore (1.29.16) hoping that would have fix the issue, but somehow still I'm getting the issue on the `StartQueryExecution`, that is super weird. [This](https://github.com/dbt-athena/dbt-athena/blob/main/dbt/adapters/athena/connections.py#L100-L107) is the call what we do in dbt-athena adapter.

**Comment by nicor88** [comment]
Closing this one, as fixed by [this](https://github.com/dbt-athena/dbt-athena/pull/56) and not realated to pyathena at all.
