### ISSUE TITLE
STS requires self.config missing attribute

### ISSUE THREAD

**Issue by maicon-berndt** [laughingman7743/PyAthena#385]
By creating a connection using ARN Role but suppressing/ignoring the optional `config` parameter PyAthena is throwing the following error message:
> AttributeError: 'Connection' object has no attribute 'config'

It happens in the line... https://github.com/laughingman7743/PyAthena/blob/15245efb8d0caaf9ccb71bc6a6ce653a090c1f76/pyathena/connection.py#L171

...once `self.config` attribute is defined with a `Config` object here... https://github.com/laughingman7743/PyAthena/blob/15245efb8d0caaf9ccb71bc6a6ce653a090c1f76/pyathena/connection.py#L142

...only after the `_assume_role` method is called: 
https://github.com/laughingman7743/PyAthena/blob/15245efb8d0caaf9ccb71bc6a6ce653a090c1f76/pyathena/connection.py#L104

I assume that the `self.config: Optional[Config] = config if config else Config()` instruction should be moved to lines above the `_assume_role` call, or the `config=self.config` parameter should be also optional by creating the `sts` client.

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/releases/tag/v2.16.1
v2.16.1 has been released. 🎉 Please check it out.
