### ISSUE TITLE
How to use session token with SQLAlchemy Connection String?

### ISSUE THREAD

**Issue by redseal798** [laughingman7743/PyAthena#387]
Hello, 

I couldn't find this in the guide. What is the correct connection string format if we want to include the `aws_session_token`?

Alternatively is there a clever way to generate a sqlalchemy connection string from a `boto3.session.Session` object?

I'm thinking something like this to take a page out from awswrangler:

```py
create_sqlalchemy_string_from_session(
    boto3_session=session,
    workgroup="workgroup",
    s3_output="s3://s3_output",
)
```

Thanks in advance.

**Comment by laughingman7743** [comment]
You should be able to pass it as a parameter named `aws_session_token` as follows:
```
awsathena+rest://{aws_access_key_id}:{aws_secret_access_key}@athena.{region_name}.amazonaws.com:443/{schema_name}?s3_staging_dir={s3_staging_dir}&aws_session_token={aws_session_token}
```

**Comment by laughingman7743** [comment]
It is not possible to pass the session object directly, but it would be easy to get the authentication information and assemble a SQLAlchemy connection string.
```
from boto3 import Session


def create_sqla_conn_string(
    session: Session, region_name: str, schema_name: str, s3_staging_dir: str
):
    creds = session.get_credentials().get_frozen_credentials()
    # TODO: The region name may be obtained from the session object.
    return (
        f"awsathena+rest://{creds.access_key}:{creds.secret_key}@athena.{region_name}.amazonaws.com:443/{schema_name}?"
        f"s3_staging_dir={s3_staging_dir}&aws_session_token={creds.token}"
    )
```
