### ISSUE TITLE
Does PyAthena support Query Result Reuse?

### ISSUE THREAD

**Issue by mjfuInrix** [laughingman7743/PyAthena#390]
Hello,

I saw there is a new option of reuse query result up to 7 days for Athena engine v3. Does PyAthena support this feature? 
    ResultReuseConfiguration={
        'ResultReuseByAgeConfiguration': {
   	    	'Enabled': True,
     		'MaxAgeInMinutes': 60
        }
    }

https://aws.amazon.com/blogs/big-data/reduce-cost-and-improve-query-performance-with-amazon-athena-query-result-reuse/

**Comment by laughingman7743** [comment]
This feature should be supported. I will implement it in the near future.
