### ISSUE TITLE
Data corruption in S3FileSystem

### ISSUE THREAD

**Issue by matthiashuschle** [laughingman7743/PyAthena#399]
Hi everyone,

I noticed some data corruption with `as_pandas` recently and tracked it down to an issue with the new `filesystem.s3.S3FileSystem`:

- The underlying caching in `fsspec` is done in the `_fetch` method of `caching.BytesCache`. If the requested range starts before the cached start, `S3File._fetch_range` is called with range `(start, cache_start)`, and then inserted in the beginning of the cache. This means, `(start, cache_start)` must not contain the byte at position `cache_start`.
- Following `_fetch_range` leads to `S3FileSystem._get_object` without modifying the end position.
- `_get_object` translates the range via: `range_ = f"bytes={ranges[0]}-{ranges[1]}"`. This differs from the original `s3fs` implementation, which reduces the end position by one. The documentation of the byte ranges (https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35) shows that the range given here is inclusive, which means the current implementation of `_get_object` gives back 1 byte more than `BytesCache._fetch` expects.
- This means that if the requested range starts before the cached start (which happens due to `BytesCache.trim` in case the requested batches are not aligned with the block size), the cache suddenly has an additional byte somewhere in the middle.

To experiment with this, you can try the following, which loads a ~100MB CSV with known structure and checks for duplicate commas or quotes:
```python
from pyathena.filesystem.s3 import S3FileSystem
from pyathena import connect
from pyathena.pandas.cursor import PandasCursor

# your AWS setup
REGION = "..."
WORK_GROUP = "..."
S3_URL = "s3://my_bucket/big.csv"

conn = connect(
    region_name=REGION,
    work_group=WORK_GROUP,
)
fs = S3FileSystem(
    conn,
    max_workers=1,
)
# open a csv on S3 with > 100 MB, that has exactly 12 double quote marks and 5 commas per line. Read in 1MB chunks.
CHUNK_SIZE = 1000000  # not dividing default batch size in fsspec (5MiB)
with fs.open(
    S3_URL,
) as file:
    for start in range(0, 100 * (2 ** 20), CHUNK_SIZE):
        file.seek(start)
        chunk = file.read(CHUNK_SIZE)
        assert all(x.count('"') == 12 for x in list(chunk.decode().splitlines())[1:-1]), start
        assert all(x.count(',') == 5 for x in list(chunk.decode().splitlines())[1:-1]), start
```

Output:
```
Traceback (most recent call last):
  File "/Users/matthiashuschle/repositories/PyAthena/show_corruption.py", line 31, in <module>
    assert all(x.count('"') == 12 for x in list(chunk.decode().splitlines())[1:-1]), start
AssertionError: 47000000
```

The obvious fix would be `{ranges[1]-1}` in `_get_object`.

**Comment by laughingman7743** [comment]
Thank you, could you make a PR for this fix?
