### ISSUE TITLE
Cursor Skips First Row When Listing Partitions

### ISSUE THREAD

**Issue by sdorazio** [laughingman7743/PyAthena#4]
Executing `SHOW PARTITIONS {table_name}` skips the the first row due to [this line of code]
(https://github.com/laughingman7743/PyAthena/blob/master/pyathena/cursor.py#L187).

The issue is really on AWS API for returning the column header as the first row in the data on `SELECT` queries. Ideally, the fix would be for them to stop returning the label as if it was part of the data set. It is not part of the data set, and they already return the column labels in the ResultSetMetadata.

One possible solution is to check for next token & if the first value is equal to the column label (or column name), skip that row (make offset = 1). I am not a fan of that, as it makes it a _magic_ value, but it would be a decent short-term fix until Amazon fixes the API.

**Comment by laughingman7743** [comment]
> One possible solution is to check for next token & if the first value is equal to the column label (or column name), skip that row (make offset = 1). I am not a fan of that, as it makes it a magic value, but it would be a decent short-term fix until Amazon fixes the API.

Thank you for suggesting implementation. I think that it is a good implementation if the specification of the current API. I will implement it on the weekend.
I hope Amazon will fix the API as soon as possible so as not to return the column label to the first row of ResultSet.

**Comment by laughingman7743** [comment]
I fixed this issue with the following pull request. 
laughingman7743/PyAthena#5

Please check it.

**Comment by sdorazio** [comment]
This looks great. Thank you!
