### ISSUE TITLE
get_table_names is filtering tables to EXTERNAL_TABLE only

### ISSUE THREAD

**Issue by bradleyhurley** [laughingman7743/PyAthena#402]
[EXTERNAL_TABLE](https://github.com/laughingman7743/PyAthena/blob/master/pyathena/sqlalchemy_athena.py#L894)

I think the [referenced](https://docs.aws.amazon.com/athena/latest/APIReference/API_TableMetadata.html) doc was misunderstood.  Athena can only create external tables, but can query tables that are considered `MANAGED_TABLE`.  For example if you're using Glue as the Hive metastore for an EMR cluster and create tables they are tagged as managed, but are fully queryable in Athena.

The `get_table_names` in the current implementation is filtering out tables that show up in the Athena UI.

**Comment by laughingman7743** [comment]
Thank you, I guess I understood the document wrong. Could you create a PR to fix this?

**Comment by laughingman7743** [comment]
Maybe it is related to this isssue.
https://github.com/laughingman7743/PyAthena/issues/394

**Comment by bradleyhurley** [comment]
It's very possible those issues are related.

Here is a [MR](https://github.com/laughingman7743/PyAthena/pull/403)

here is some sample code to help check if this is the issue in #394. If the results show the tables as expected and the type is not EXTERNAL then its the same issue/

```
import sqlalchemy as sa
from sqlalchemy.engine import create_engine

conn_str = "awsathena+rest://@athena.us-west-2.amazonaws.com:443/<<database-name>>?work_group=<<workgroup-name>>"
engine = create_engine(conn_str)
with engine.connect() as connection:
    inspector = sa.inspect(engine)
    assert "<<database_name>>" in inspector.get_schema_names()
    tables = inspector.dialect._get_tables(connection=inspector.engine, schema="<<database_name>>")
    print([f"{t.name}: {t.table_type}" for t in tables])
```
