### ISSUE TITLE
What is s3_staging_dir, and why does pyathena need it?

### ISSUE THREAD

**Issue by roncemer** [laughingman7743/PyAthena#409]
Seriously...requiring me to provide s3_staging_dir just to run queries against Athena in Python is beyond ridiculous.

Also, it's just leaving a bunch of garbage files in that directory.  Why?

Make s3_staging_dir optional, and document it as such.

**Comment by laughingman7743** [comment]
Please refer to the official AWS documentation.
https://docs.aws.amazon.com/athena/latest/ug/querying.html
Then, as a feature request to Athena, you can request AWS support not to output the query results to S3. I did not create this specification.

**Comment by laughingman7743** [comment]
Why would you create such an Issue without even checking the official documentation? 
The title of the Issue also uses swear words and is very offensive.
