### ISSUE TITLE
pyathena.connect() call returns Cursor

### ISSUE THREAD

**Issue by spicy-jmr** [laughingman7743/PyAthena#41]
When calling pyathena.connect(), the connection's _Cursor_ object is returned instead of the expected _Connection_ object.

Experienced in version 1.2.5

**Comment by laughingman7743** [comment]
The connection object seems to be returned. 🤔 
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/__init__.py#L54
Please show the source code when the cursor object is returned.

**Comment by spicy-jmr** [comment]
Yes, I was also working on the assumption that Connection is returned. The following are the relevant excerpts from within the code (the get_conn method is within a Connection Manager class):

`from pyathena import connect as athena_connect

def get_conn(self, database_name, creds_key):
    return athena_connect(
        aws_access_key_id=self.passwords[creds_key]['un'],
        aws_secret_access_key=self.passwords[creds_key]['pw'] if not self.decrypt_key else
        decrypt(self.decrypt_key, self.passwords[creds_key]['pw']).decode("utf-8"),
        s3_staging_dir=athena_us_east_1[database_name],
        region_name='us-east-1'
    )
`

and the excerpts of calling code which is throwing an error:

`
with connection_manager_instance.get_conn(db_name, key) as athena_conn:
    self.src_cursor = self.athena_conn.cursor()`

error thrown is basically that Cursor object has no method cursor()

Do note, that I'm using all of this within a larger class which also utilizes another DB API 2.0 compliant package (pyhive.presto) which returns connection class when the same above format is used. I suspect the issue might be within your 
connection.py __enter__()
since there you return the cursor and not the connection; thus, unexpected behaviour when used in a 'with -- as' block.

**Comment by laughingman7743** [comment]
Oh, the context manager will certainly return a cursor object.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L82

PyMySQL and mysqlclient-python return a cursor object.
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L497
https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/connections.py#L284

Which one of a cursor object and a connection object should be returned? It seems that the specification of the context manager is not written in PEP 249. 🤔

**Comment by spicy-jmr** [comment]
Interesting; I've been using psycopg2 within context extensively, as it helps maintain clean connection lifecycles; however it does require that connection object, so that the commits/rollbacks can get called on the connection. True, this use-case may not be applicable with Athena connections, however.

Food for thought. Receiving a cursor instead of a connection when a call to connect() is made seems counter-intuitive. I would propose at the very least adding that usage example in the documentation, to clarify that distinction: when calling connect() in context you receive the cursor object back, but without the context, you must explicitly call Connection.cursor();

**Comment by laughingman7743** [comment]
I think that returning a connection object is simpler and easier to understand.
I will fix it on the weekend. 😆 

Thanks,

**Comment by laughingman7743** [comment]
I fixed it. Please check the pull requests https://github.com/laughingman7743/PyAthena/pull/43 .
