### ISSUE TITLE
Detect query type from raw SQL/DML/DDL

### ISSUE THREAD

**Issue by ni-todo-spot** [laughingman7743/PyAthena#413]
Hello,

As part of the project I'm working on, I'd like a way to allow end users of my project to execute sql statements over my athena server.

End users can interact with my athena server via a webpage I made.

The risk of such idea is that users may try to execute statement like: "DROP TABLE ...".

So my question: Is there a way using pyathena (or boto3) to detect a non read only queries (basically anything which is not SELECT ...) before trying to execute it?
I'm looking for a solution which covers any DML / DDL statement

Thanks in advance!

**Comment by laughingman7743** [comment]
You can use queries with placeholders or use SQLAlchemy to assemble your query. 
https://github.com/laughingman7743/PyAthena#query-with-parameter
Do not assemble your query using string concatenation.

**Comment by laughingman7743** [comment]
https://github.com/andialbrecht/sqlparse
https://github.com/macbre/sql-metadata
It should be possible to use such an SQL parser to parse queries to determine DDL or DML could be determined; it is unlikely that the DB-API would support such a feature.
