### ISSUE TITLE
Is it possible to use both unload and chunksize?

### ISSUE THREAD

**Issue by innicoder** [laughingman7743/PyAthena#416]

**Comment by laughingman7743** [comment]
If you use the unload option, you will be reading a file in Parquet format, using Pandas' read_parquet method, which does not seem to have a chunksize option.
https://pandas.pydata.org/docs/reference/api/pandas.read_parquet.html
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/pandas/result_set.py#L322

Checking StackOverflow, I find the following question:
https://stackoverflow.com/questions/59098785/is-it-possible-to-read-parquet-files-in-chunks
For ArrowCursor, the implementation is such that the arraysize is the batch size.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/arrow/result_set.py#L82
I don't know if such an option can be specified for PandasCursor. If you know, please let me know.

**Comment by laughingman7743** [comment]
The method get_pandas does not exist in PyAthena, but is this code what you are actually running? Can you tell me how you create the connection object and how you set up the cursor class?
```
pyathena.execute(f"select * from cars where {car}").get_pandas()
```

The connection pool problem can be solved by increasing max_pool_connections in the boto3 config.
https://github.com/boto/botocore/issues/619
You can pass a boto3 config to the connection object.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L68

**Comment by laughingman7743** [comment]
Even if chunksize is specified, if all dataframes are eventually concatenated, memory usage is not likely to change. If some processing is done for each chunksize of dataframe, it would make sense to specify chunksize.
