### ISSUE TITLE
Option to NOT save header in s3 staging

### ISSUE THREAD

**Issue by ianchute** [laughingman7743/PyAthena#437]
Is there a way to **NOT** save the header to s3 staging?

My use case for this is for pyathena to write what I need to s3 staging, 
and then immediately use the generated data and result path in some subsequent AWS operation.

```python
from pyathena import connect

dest = "s3://mybucket/mypath/"
cursor = connect(s3_staging_dir=dest,
                 region_name="us-west-2").cursor()
cursor.execute("SELECT * FROM table1", staging_header=False) # blocking operation
result_path = dest + cursor.query_id + ".csv"

import boto3
client = boto3.client("some_aws_service")
client.do_something(result_path)
```

Would appreciate any help!

**Comment by laughingman7743** [comment]
The CSV output to the staging directory is not output by this library, so it is not possible to control the existence of headers.
https://docs.aws.amazon.com/athena/latest/ug/unload.html
You may want to use the UNLOAD statement.
