### ISSUE TITLE
boto3 and botocore

### ISSUE THREAD

**Issue by joseph-wortmann** [laughingman7743/PyAthena#44]
This is a fantastic piece of work! One minor issue regarding using this in a Lambda function.

Packaging boto3 and botocore into a python lambda function is not a good idea due to the rate of change that the AWS API experiences. What happens is that eventually a long-running Lambda function will start failing in weird ways due to old boto and new API incompatibilities.

I'm trying to use your package in a lambda function, but the resulting Lambda package is (obviously) pulling in the boto stuff when I include your stuff.

Would it be too much to ask for you to remove the boto stuff from the install_requires portion, and either move it to extras_requires or simply document that you require it?

I'm happy to do a PR for this if you want me to, or fork and modify (I don't prefer this).

Your consideration is much appreciated!
-Joe

**Comment by laughingman7743** [comment]
This library depends on botocore and boto3. I do not want to upload the library that does not work just by installing it to PyPI.
When packaging Lambda you should remove botocore and boto3? I think that you can handle it with a packaging script.

Thanks,

**Comment by joseph-wortmann** [comment]
I understand. There's really no clean solution.

It really can't be well managed (or managed at all) with packaging scripts. Boto has a bunch of stuff it pulls in, there's no way to really know if other packages need some of those sub-deps, and pip doesn't provide a way to blacklist discrete packages. Pip is great for many things, but for this level of specificity it sucks.

I'll fork your stuff to a lambda-pyathena package for use in AWS Lambda.

Thanks for creating this - its been awesome to work with so far.

Joe
