### ISSUE TITLE
AttributeError: type object 'AthenaRestDialect' has no attribute 'dbapi'

### ISSUE THREAD

**Issue by dominik-reiner** [laughingman7743/PyAthena#456]
Hi,
this relates to https://github.com/laughingman7743/PyAthena/issues/447#issuecomment-1612552725.

I am running SQLAlchemy 1.4.48 and PyAthena 3.0.3.

When trying to create an engine as shown below I get an error:
AttributeError: type object 'AthenaRestDialect' has no attribute 'dbapi'

```
from sqlalchemy.engine import create_engine

conn_str = "awsathena+rest://{aws_access_key_id}:{aws_secret_access_key}@athena.{region_name}.amazonaws.com:443/"\
            "{schema_name}?s3_staging_dir={s3_staging_dir}"

engine = create_engine(conn_str.format(
  aws_access_key_id="XXX",
  aws_secret_access_key="XXX",
  region_name="eu-central-1",
  schema_name="default",
  s3_staging_dir="s3://XXX")
)
```

Here is the traceback:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[10], line 6
      1 from sqlalchemy.engine import create_engine
      3 conn_str = "awsathena+rest://{aws_access_key_id}:{aws_secret_access_key}@athena.{region_name}.amazonaws.com:443/"\
      4             "{schema_name}?s3_staging_dir={s3_staging_dir}"
----> 6 engine = create_engine(conn_str.format(
      7     aws_access_key_id="XXX",
      8     aws_secret_access_key="XXX",
      9     region_name="eu-central-1",
     10     schema_name="default",
     11     s3_staging_dir="s3://XXX"))

File :2, in create_engine(url, **kwargs)

File /opt/homebrew/Caskroom/miniforge/base/envs/xxx/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py:375, in deprecated_params..decorate..warned(fn, *args, **kwargs)
    368     if m in kwargs:
    369         _warn_with_version(
    370             messages[m],
    371             versions[m],
    372             version_warnings[m],
    373             stacklevel=3,
    374         )
--> 375 return fn(*args, **kwargs)

File /opt/homebrew/Caskroom/miniforge/base/envs/xxx/lib/python3.9/site-packages/sqlalchemy/engine/create.py:541, in create_engine(url, **kwargs)
    539 if dbapi is None:
    540     dbapi_args = {}
--> 541     for k in util.get_func_kwargs(dialect_cls.dbapi):
    542         if k in kwargs:
    543             dbapi_args[k] = pop_kwarg(k)

AttributeError: type object 'AthenaRestDialect' has no attribute 'dbapi'

**Comment by mdeshmu** [comment]
@laughingman7743 PR raised https://github.com/laughingman7743/PyAthena/pull/457
Please let me know how the tests behave.

**Comment by laughingman7743** [comment]
Thanks, I'll see if all the tests pass.
