### ISSUE TITLE
Fetching large result sets can be sped up massively using S3

### ISSUE THREAD

**Issue by jkleint** [laughingman7743/PyAthena#46]
Hello, thanks for such a great library; it has really made working with Athena from Python easy.

I download a lot of large results from Athena queries (in the gigabyte range).  Unfortunately, using PyAthena for this is very (very) slow -- hundreds of times slower than just downloading the results from S3. This is because it is fetching and converting a few rows at a time via the Athena API.

I have taken to working around it with the following approach.  Basically, execute the query, get the output location, then fetch with S3 (and convert to Pandas in my case).

```
from smart_open import smart_open  # pandas can't easily read from S3 using a role/profile

athena_cursor = pyathena.connect(...).cursor()

def query(sql, profile=None):
    """:Return: a Pandas DataFrame of results from a `sql` query executed against AWS Athena."""
    athena_cursor.execute(sql)
    # MUCH faster than PyAthena reading a few rows at a time via the API
    return pd.read_csv(smart_open(athena_cursor.output_location, profile_name=profile))
```

(I'm using [smart_open](https://github.com/RaRe-Technologies/smart_open) to make fetching from S3 easy, but of course the same thing can be accomplished with just boto.)

Could something like this be incorporated directly into PyAthena?  Perhaps `connect` could have an option `fetch_with_s3=True` or similar.  You'd probably still need to do type conversion, but there could be a fast path for `as_pandas()` to let Pandas do it all in one go.

Just a thought; thanks again!

**Comment by laughingman7743** [comment]
It would be nice to create a new `PandasCursor` like `AsyncCursor`.
```
cursor = connect(s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',
                 region_name='us-west-2',
                 cursor_class=PandasCursor).cursor()
df = cursor.execute("SELECT * FROM many_rows").as_pandas()
```
When the execution of the query is completed, the cursor will download CSV from S3 on memory, set data in read_csv, and return dataframe.
I think that it would be easy to implement if such a cursor. It is not a cursor anymore.
Is `smart_open` faster than downloading CSV in `boto3`?

**Comment by laughingman7743** [comment]
By the way, the performance of JDBC driver seems to be improved.
https://aws.amazon.com/about-aws/whats-new/2018/08/amazon-athena-streaming-jdbc-driver/

PyAthenaJDBC is releasing v2.0.0 which corresponds to the new driver.
https://github.com/laughingman7743/PyAthenaJDBC/releases/tag/v2.0.0
Would you be willing to check performance?

**Comment by jkleint** [comment]
I tried PyAthenaJDBC, and it connects, but it just hangs executing a query (PyAthena works fine).  Seems to hang at [cursor.py:118](https://github.com/laughingman7743/PyAthenaJDBC/blob/master/pyathenajdbc/cursor.py#L118) running `statement.execute()`.  I'm not very familiar with JDBC, so I may be missing something basic.  Do I need to do anything besides `pipenv install PyAthenaJDBC`?

I may look into writing a new cursor.  Thanks!

**Comment by laughingman7743** [comment]
It will work if Java is installed. JDBC does not necessarily require any special environment.
It seems like a problem with your network environment. 🤔 

I tried implementing PandasCursor. Please check the following branch.
laughingman7743/PyAthena/pull/47

**Comment by jkleint** [comment]
That looks great.  One further bit is that this leaves pandas to guess the column types, but it's not always possible.  Here's what I'm using to convert sql types to pandas types:

```
from decimal import Decimal
from binascii import unhexlify
import json

SQL_PANDAS_TYPES = {
    'boolean': bool,
    'tinyint': int,
    'smallint': int,
    'integer': int,
    'bigint': int,
    'float': float,
    'real': float,
    'double': float,
    'char': str,
    'varchar': str,
}

SQL_PANDAS_CONVERTERS = {
    'decimal': Decimal,    
    'varbinary': lambda b: unhexlify(b.replace(' ', '')),
    'json': json.loads,
}


def read_sql_csv(csvfile, sqltypes):
    """:Return: a Pandas DataFrame made from `csvfile` using the "dtypes" from a dict
    `{colname: sqltype}` giving the SQL type of each column."""
    dtype = {col: SQL_PANDAS_TYPES[sqltype] for col, sqltype in sqltypes.items() if sqltype in SQL_PANDAS_TYPES}
    converters = {col: SQL_PANDAS_CONVERTERS[sqltype] for col, sqltype in sqltypes.items() if sqltype in SQL_PANDAS_CONVERTERS}
    parse_dates = [col for col, sqltype in sqltypes.items() if sqltype in ('date', 'time', 'timestamp', 'time with time zone', 'timestamp with time zone')]
    times = [col for col, sqltype in sqltypes.items() if sqltype in ('time', 'time with time zone')]   # parse_dates will add today's date to pure times
    result = pd.read_csv(csvfile, dtype=dtype, parse_dates=parse_dates, converters=converters, infer_datetime_format=True)
    result.loc[:, times] = result.loc[:, times].apply(lambda r: r.dt.time)
    return result
```

(Pandas `read_csv()` isn't very consistent about types and conversion, so you have to special-case dates/times and a few others.)

I left array, map, and row types as strings since Athena's CSV representation of these types is ambiguous, so there's no way to parse them correctly.  (I suggest `cast(col as json)` if you want to use complex types.)

Then you call it like:

```
sqltypes = dict(desc[0:2] for desc in cursor.description)
read_sql_csv(csvfile, sqltypes) 
```

I haven't tested this thoroughly, or on Python 2 (but I tried to make it 2/3 compatible).

**Comment by laughingman7743** [comment]
Thanks for the nice advice.
I tried to implement type conversion with reference to your code. And I wrote tests.
Please check the branch. Thanks!

**Comment by jkleint** [comment]
Hey that was fast!  Thank you for your work.

I tried it on a table containing timestamps, and unfortunately it was still very slow.  Looking into it, all the time was spent parsing datetimes.  I noticed you used `dateutil` as a converter.  When using `converters=...`, they are called one at a time on each value, with slow Python code.   When you use Pandas' `parse_dates=...`, it's using fast vectorized C code.   A quick test shows that Pandas' date parsing is over 60X faster than `dateutil.parser.parse` .

```python
import io
from dateutil.parser import parse

csv = io.StringIO()
pd.Series(pd.date_range('2018-01-01', '2019-01-01', freq='min')).to_csv(csv, index=False, header=['time'])
csv.seek(0)
%time df = pd.read_csv(csv, parse_dates=['time'])
csv.seek(0)
%time df = pd.read_csv(csv, converters={'time': parse})
```

```
CPU times: user 723 ms, sys: 69.7 ms, total: 793 ms
Wall time: 793 ms
CPU times: user 50 s, sys: 276 ms, total: 50.3 s
Wall time: 50.3 s
```

That's why I went out of my way to special case dates in my code; using vectorized date parsing is much faster, even when you have to go back and pull out the times.

**Comment by laughingman7743** [comment]
Oh, dateutils.parser.parse is very very slow. 😱
I understood why you are parsing the datetime type in Pandas.
Fixed parsing of datetime type. Are there any other performance problems?

**Comment by jkleint** [comment]
Yeah, it's working very well!  Thank you so much, Will test a bit more next week.

**Comment by laughingman7743** [comment]
I checked the performance.
https://gist.github.com/laughingman7743/2e4d83ca4e394dc645e9ea9a45fe78ba
PandasCursor is ultra fast. 😆

**Comment by jkleint** [comment]
Over 13X faster, impressive!  Thank you again for this.  You are a fantastic open source maintainer, it was a pleasure working with you and with your software.
