### ISSUE TITLE
Add LIMIT as argument for execute

### ISSUE THREAD

**Issue by nicor88** [laughingman7743/PyAthena#467]
With the introduction of dbt-core 1.6.0 we need to be able to pass a limit parameter to athena cursor, therefore will be nice to have that in place directly in pyathena.

I didn't find that possible, but happy to close this one if it's already implemented.

**Comment by laughingman7743** [comment]
I don't know what your requirements are, but I don't see why this library would need to be implemented specifically for dbt.

**Comment by nicor88** [comment]
I' was just giving you a context of use case for that.
I'm just "asking" if it's possible to "add" "limit" to AthenaCurson.execute - potentially uses cases is not only dbt BUT a broader users pool.

e.g. `AthenaCurson.execute(sql, limit=100)`

**Comment by laughingman7743** [comment]
The cursor's execute method is an interface to execute a user-specified query. A query is not only a SELECT statement. It is not possible to support such parameters. If you want to embed parameters in your query, you can use named placeholders.
https://github.com/laughingman7743/PyAthena#query-with-parameter
