### ISSUE TITLE
Implement all fsspec specs in the s3 file system

### ISSUE THREAD

**Issue by laughingman7743** [laughingman7743/PyAthena#483]
https://github.com/laughingman7743/PyAthena/issues/465

**Comment by vikalfc** [comment]
Hi, can I get some updates on this issue? I would really appreciate if you can fix it, I'm using .as_pandas() in my code with version 2.17.0 and everything is perfect :) TY

**Comment by thefabnab** [comment]
@laughingman7743 since this issue is still open I'm guessing you haven't made much progress on it?

**Comment by laughingman7743** [comment]
Japan is on holiday for the next two weeks or so. I'm planning to implement this.
