### ISSUE TITLE
Add custom filesystem object to arrow engine

### ISSUE THREAD

**Issue by jayceslesar** [laughingman7743/PyAthena#485]
pyarrow 13.0.0 doesnt work with AWS SSO but my org has a custom filesystem object that does, how could I go about injecting my custom s3 filesystem into pyathena instead of using the default one provided.

```py
with engine.connect() as conn:
# How can I inject here?
```

**Comment by jayceslesar** [comment]
see https://github.com/apache/arrow/issues/38013

**Comment by laughingman7743** [comment]
It cannot be changed to a custom S3 file system.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/arrow/result_set.py#L86-L114
