### ISSUE TITLE
Compatibility issue with SQLAlchemy<1.4

### ISSUE THREAD

**Issue by stlee-aurora** [laughingman7743/PyAthena#490]
Hello! I believe I have encountered a breaking compatibility issue between PyAthena>=3.0 and SQLAlchemy<1.4. My use case currently requires Python 3.10 and SQLAlchemy<1.4, so this issue prevents me from using PyAthena with SQLAlchemy.

A reproducible example:
Python version 3.10.12
`pyathena==3.0.10`
`sqlalchemy==1.3.24`

When I execute:
`from pyathena.sqlalchemy.base import AthenaDialect`

I receive:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stlee/venv_test/pyathena/lib/python3.10/site-packages/pyathena/sqlalchemy/base.py", line 39, in <module>
    from pyathena.sqlalchemy.types import AthenaDate, AthenaTimestamp
  File "/home/stlee/venv_test/pyathena/lib/python3.10/site-packages/pyathena/sqlalchemy/types.py", line 15, in <module>
    class AthenaTimestamp(TypeEngine[datetime]):
TypeError: 'VisitableType' object is not subscriptable
```

**Comment by laughingman7743** [comment]
You may want to update SQLAlchemy to 1.4. Or use an older version of PyAthena; the latest version of PyAthena does not support SQLAlchemy 1.3.

If the error occurs in SQLAlchemy 1.4, please register the issue.

**Comment by stlee-aurora** [comment]
Got it, thanks for the response! I would suggest updating the version requirements for `sqlalchemy` in the setup configuration.
