### ISSUE TITLE
`UUID` in a query gets garbled

### ISSUE THREAD

**Issue by sevanteri** [laughingman7743/PyAthena#492]
Just upgraded from 3.0.8 to 3.0.10 and it seems handling UUIDs broke.

```python
[ins] In [1]: from pyathena.sqlalchemy.base import AthenaDialect

[ins] In [2]: import sqlalchemy as SQA

[ins] In [3]: import uuid

[ins] In [4]: query = SQA.select(SQA.literal(uuid.UUID(int=0)))

[ins] In [5]: str(query.compile(dialect=AthenaDialect(), compile_kwargs={"literal_binds": True}))
Out[5]: "SELECT '00000000000000000000000000000000' AS anon_1"
```

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/compare/v3.0.8...v3.0.10
Is there any change that might be related to this? 🤔 
It may be a different version of SQLAlchemy. I need more information to investigate.

**Comment by sevanteri** [comment]
Hmmh... could also be SQLAlchemy. Just checked and we also upgraded that.

Seems like at least mysql and sqlite dialects do the same thing. Postgresql dialect doesn't.

**Comment by sevanteri** [comment]
Okay this is clearly not an issue in pyAthena but somewhere in SQLAlchemy, or my brain. I'll just close this, at least for now.
