### ISSUE TITLE
SQLAlchemy dialect uses deprecated dbapi() method

### ISSUE THREAD

**Issue by 0Itsuki0** [laughingman7743/PyAthena#496]
Getting the following warning while using create_engine(). 
It appears that this library is using a deprecated method from SQLAlchemy:

`SADeprecationWarning: The dbapi() classmethod on dialect classes has been renamed to import_dbapi().  Implement an import_dbapi() classmethod directly on class <class 'pyathena.sqlalchemy.rest.AthenaRestDialect'> to remove this warning; the old .dbapi() classmethod may be maintained for backwards compatibility.`

**Comment by laughingman7743** [comment]
Please review the following issues and PRs.
- https://github.com/laughingman7743/PyAthena/issues/447
- https://github.com/laughingman7743/PyAthena/issues/456
- https://github.com/laughingman7743/PyAthena/pull/457
Required for compatibility with SQLAlchemy 1.4 series.
