### ISSUE TITLE
Okta authentication support

### ISSUE THREAD

**Issue by jinserk** [laughingman7743/PyAthena#512]
I'm curious if `pyathena` supports Oka authentication as desribed here:
https://docs.aws.amazon.com/athena/latest/ug/jdbc-v3-driver-okta-credentials.html

If not, do you have any plan to support this?

**Comment by laughingman7743** [comment]
It is a feature of the JDBC driver. The following tools would be good to use.
https://github.com/godaddy/aws-okta-processor
PyAthena will not support it.
