### ISSUE TITLE
[Warning] SADeprecationWarning: The dbapi() classmethod on dialect classes has been renamed to import_dbapi().

### ISSUE THREAD

**Issue by moshe-shelly** [laughingman7743/PyAthena#528]
I'm using the library via SQLDatabase (from langchain_community.utilities)

Getting the following warning:

SADeprecationWarning: The dbapi() classmethod on dialect classes has been renamed to import_dbapi().  Implement an import_dbapi() classmethod directly on class <class 'pyathena.sqlalchemy.rest.AthenaRestDialect'> to remove this warning; the old .dbapi() classmethod may be maintained for backwards compatibility.

I think this here is where the change should be implemented:
https://github.com/laughingman7743/PyAthena/blob/cb901047861cda020d481430d08699300e61831d/pyathena/sqlalchemy/base.py#L1016

Thanks!

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/issues/496
