### ISSUE TITLE
Cursor doesn't support setting OutputLocation

### ISSUE THREAD

**Issue by aidin36** [laughingman7743/PyAthena#53]
Default `OutputLocation` is the same path as table's location. It shouldn't be possible to set the location to somewhere else.

An example is when a user has `read-only` access to the table (and it's related S3). User cannot write to that S3 address, so it need to set `OutputLocation` to somewhere else.

**Comment by laughingman7743** [comment]
Thanks PR!
When creating a connection object, is it not enough to explicitly specify `s3_staging_dir`? I do not understand the use case for specifying the location of S3 with the cursor object.
