### ISSUE TITLE
URLLIB3 / Requests

### ISSUE THREAD

**Issue by VeNoMouS** [laughingman7743/PyAthena#535]
Can we get rid of your outdated urrlib3 etc from requirements if botocore is now using newer versions, since you already require botocore why not let them dictate required modules since you dont import urllib3 / requests yourself...

you're killing me with having to do forced updates after your package updates.

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/blob/master/pyproject.toml#L7-L12
This library has no direct dependencies with urllib3.

**Comment by VeNoMouS** [comment]
Then why include them [https://github.com/laughingman7743/PyAthena/blob/master/requirements/requirements.txt#L921] (https://github.com/laughingman7743/PyAthena/blob/master/requirements/requirements.txt#L921) as requirements

**Comment by laughingman7743** [comment]
That's a dependency of the environment for developing this library. This library has no direct urllib3 or requests dependencies.
https://github.com/laughingman7743/PyAthena/blob/master/pyproject.toml#L83-L101

**Comment by laughingman7743** [comment]
https://github.com/boto/botocore/blob/develop/setup.py#L25-L33
botocore has a dependency on urllib3; it would be good to ask botocore to improve it.
