### ISSUE TITLE
Formatter does not escape single quotes when operation is MERGE or UPDATE

### ISSUE THREAD

**Issue by Oskar-Bonde** [laughingman7743/PyAthena#537]
Currently strings with single quotes are not formatted correctly when the operation is MERGE or UPDATE. 
Created pull request #536 to solve this issue.

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/releases/tag/v3.7.0
https://pypi.org/project/PyAthena/3.7.0/
I just released v3.7.0.
