### ISSUE TITLE
Feature request: support for positional parameter substitution

### ISSUE THREAD

**Issue by paulgrow-octane** [laughingman7743/PyAthena#545]
Thank you for a wonderful library and for your work maintaining it!

One feature I hope can be considered for future development is implementing `?` style param support. Athena supports [parameterized queries](https://docs.aws.amazon.com/athena/latest/ug/querying-with-prepared-statements.html) using the `?` character for positional substitution.

For use cases where queries are run both using `pyathena` and by analysts directly, having `PyFormat`-style params is not ideal as it requires analysts to modify queries to execute them directly in their SQL clients or in the Athena console. Supporting `?` for query parameterization would decouple the query from any specific execution context, making it more portable.

Thanks for your time and consideration.

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/__init__.py#L19
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/common.py#L558-L566
If the paramstyle is set to qmark, I think it can be handled by simply stopping the expansion of the query parameters and passing the parameters to the start_query_execution request.
I think this could be easily implemented without major changes. I will probably address this eventually when I have time.
