### ISSUE TITLE
How to connect using VPC endpoint?

### ISSUE THREAD

**Issue by mrcolumbia** [laughingman7743/PyAthena#559]
Athena allows for the use of VPC endpoints to improve security: https://docs.aws.amazon.com/athena/latest/ug/interface-vpc-endpoint.html. How can I use this library when connecting to such endpoints (i.e. VPC_Endpoint_ID.athena.Region.vpce.amazonaws.com)?

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/issues/495#issuecomment-1874905322

**Comment by mrcolumbia** [comment]
Tried the following (I do not have a access key ID or secret access key with our current setup):

```
conn_str = "awsathena+rest://@athena.{region_name}.amazonaws.com:444/" \
               "{schema_name}?s3_staging_dir={s3_staging_dir}&endpoint_url={endpoint_url}"
			   
engine = create_engine(conn_str.format(
	region_name="...",
	schema_name="...",
	s3_staging_dir="...",
	profile_name="...",
	endpoint_url="...")
)

conn = engine.connect()
conn.execute(text('select * ...'))
```

Got this error:

`sqlalchemy.exc.DatabaseError: (pyathena.error.DatabaseError) An error occurred (UnrecognizedClientException) when calling the StartQueryExecution operation: The security token included in the request is invalid.`

**Comment by laughingman7743** [comment]
I am not sure what authentication method you have chosen to use with this library. The error probably has nothing to do with this library, it looks more like an SSO authentication has expired after a period of time or something like that.

**Comment by mrcolumbia** [comment]
I think you missed my update above - I was able to resolve the issue. Thanks.
