### ISSUE TITLE
MAP and ARRAY types in Athena Iceberg

### ISSUE THREAD

**Issue by thezachdrake** [laughingman7743/PyAthena#567]
Is there a current good way to use the MAP and ARRAY types in Athena through sqlalchemy? We would like to use the SQL Alchemy ORM if possible. When testing the JSON and ARRAY types did not work with queries run against Athena. I can see that there are not types implemented in the PyAthena source code directly. Are these useable in some other way?

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/issues/553
