### ISSUE TITLE
Cursor doesn't support config property

### ISSUE THREAD

**Issue by m-for-madness** [laughingman7743/PyAthena#64]
Hey @laughingman7743! 
First of all thank you for such a good tool to work with Athena.
Now o would like to come back to the problem.
When i am trying to pass 'config' property for `boto3.client` as element of kwargs 
`pyathena.connect(s3_staging_dir=env['athena_staging_dir'], region_name=env['region'], config=env['config'])`, it fails because Session constructor unpack kwargs parameter and there is no 'config' argument. So it couldn't reach boto3.client in `connection.py`.
Could we fix this problem by using `_get_default_session` as it is implemented in boto3? Or we could add  some properties to constructor in `connection.py` , because now we can't use any of kwargs which are optional in `boto3.client`

**Comment by laughingman7743** [comment]
Would you solve it by passing unpacked values as arguments?
```
pyathena.connect (s3_staging_dir = env ['athena_staging_dir'], region_name = env ['region'], ** env ['config'])
```
What value is entered in config? I want a code example.

**Comment by m-for-madness** [comment]
` import pyathena
from botocore.config import Config

client = pyathena.connect(s3_staging_dir=env['athena_staging_dir'], region_name=env['region'], config=Config(proxies={'https': proxy}))`

It fails with error 
'__init__() got an unexpected keyword argument 'config': TypeError Traceback'

I tried to pass it unpacked, but the same issue occurred.

**Comment by laughingman7743** [comment]
I see. Surely the Session object of boto3 does not accept the `config` argument.
https://github.com/boto/boto3/blob/develop/boto3/session.py#L48

The profile name can only be specified with the Session object.
Do you have any ideas as a workaround?

**Comment by laughingman7743** [comment]
I fixed it. Please check the following branches.
https://github.com/laughingman7743/PyAthena/pull/66

**Comment by m-for-madness** [comment]
Great! It works! 

Thank you! 

P.S. Sorry for ignore, i was rly busy... 
Nevertheless you do a lot of work. Thank you for that.
