### ISSUE TITLE
Unable to verify/create output bucket

### ISSUE THREAD

**Issue by timnon** [laughingman7743/PyAthena#67]
I am not sure if this is a pyathena problem or a problem of the AWS rights or sth completely else.

The following error happens sometimes (sometimes it also works, its really non-deterministic):
```
pyathena.error.DatabaseError: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Unable to verify/create output bucket <my-output-bucket>
``` 
The strange thing is that it might work for a few days, and then this error occurs again. I have no idea why this happens (the AWS user has write rights to the bucket, it works sometimes, so this is correct). I added rights to AWS Glue because it was suggested in some forum, but it didnt help.

Also any hints how to debug this problem are appreciated.

**Comment by markjusik** [comment]
Hi, could you share the full error output?

**Comment by m-for-madness** [comment]
Hi, could you share the full error output?

**Comment by timnon** [comment]
I reproduced it with only boto3, so its not a problem with pyathena. The full error output is:
```
Traceback (most recent call last):
  File "athena.py", line 19, in <module>
    run_query(query,"clickstream","s3://<our athena staging bucket>")
  File "athena.py", line 12, in run_query
    'OutputLocation': s3_output,
  File "/opt/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Unable to verify/create output bucket <our athena staging bucket>
```
However, the strange this is that if i use another user (other AWS key-secret pair) to run this query straight afterwards, i dont get this errror but the query runs fine. Returning then immediately to the original user makes the query also work????

I guess this is definitely not a pyathena problem, so i will close this issue. However, strange things are happening here.

**Comment by timnon** [comment]
This might even be a general S3 access problem independent of Athena. Pretty hard to test, since i need to wait until the used fails again.
