### ISSUE TITLE
Using WorkGroup in API requests

### ISSUE THREAD

**Issue by sharath-thirunagaru** [laughingman7743/PyAthena#69]
Hi, 

Athena WorkGroup allows you to isolate queries for teams, applications etc. You can read more about Athena WorkGroup here https://docs.aws.amazon.com/athena/latest/ug/user-created-workgroups.html.  I don't see a way to submit a query in particular `WorkGroup` rather than the `primary` which is default. 

```python
from pyathena.connection import Connection
conn = Connection(s3_staging_dir='s3://test/',region_name='us-east-1')
cur = conn.cursor(WorkGroup='test')
cur.execute('select * from test.table2') # this submits query in primary workgroup rather than test
```

**Comment by laughingman7743** [comment]
https://docs.aws.amazon.com/ja_jp/athena/latest/ug/workgroups-create-update-delete.html#specify-wkgroup-to-athena-in-which-to-run-queries
https://docs.aws.amazon.com/ja_jp/athena/latest/APIReference/API_StartQueryExecution.html

**Comment by sharath-thirunagaru** [comment]
Yes, I can start a query from `boto3` Athena client in required WorkGroup like below. But, I was looking for something with this module that allows this.

```python
import boto3
athena = boto3.client('athena')
athena.start_query_execution(
    QueryString='select * from test.table2',
    WorkGroup='test'
)
```

**Comment by laughingman7743** [comment]
I tried supporting the `work_group` parameter on the following branch.
https://github.com/laughingman7743/PyAthena/pull/72
Please check it.
