### ISSUE TITLE
Pyathena encryption with kms key is not working

### ISSUE THREAD

**Issue by chgangaraju** [laughingman7743/PyAthena#70]
I am querying Athena using `PyAthena-1.4.6`. 

    connection = connect(
        s3_staging_dir='s3://' + athena_results_s3_bucket + '/athena_results',
        region_name=region,
        encryption_option='SSE-KMS',
        kms_key=kms_key
    )
    cursor = connection.cursor()
    cursor.execute(sql_query)

I am able to query the data, but the data in s3 staging_dir is not encrypted. I tried all possible values for 'encryption_opion'. I could not find any documentation for this.
`

**Comment by laughingman7743** [comment]
https://docs.aws.amazon.com/athena/latest/ug/encryption.html
> You can run queries in Athena to query encrypted data in Amazon S3 by indicating data encryption when you create a table. You can also encrypt the query results in Amazon S3, and the data in the AWS Glue Data Catalog. 
It is not an option to encrypt the query result output to `s3_staging_dir`.

**Comment by laughingman7743** [comment]
https://docs.aws.amazon.com/athena/latest/ug/encryption.html#encrypting-query-results-stored-in-s3
https://docs.aws.amazon.com/athena/latest/ug/workgroups-settings-override.html
I think that this is the encryption setting of the query result.

**Comment by chgangaraju** [comment]
Thank you for the reply. I am looking for the **Client-side settings**. Since we are passing query results location from the client and we should be able to provide encryption also.

> Client-side settings. When you use Settings in the console or the API operations to indicate that you want to encrypt query results, this is known as using client-side settings. **Client-side settings include query results location and encryption**. If you specify them, they are used, unless they are overridden by the workgroup settings.

 Since we are passing **query results location** (s3_staging_dir) from the client and we should be able to send **encryption** also.

I have data in S3 encrypted with specific KMS, but i am able to query without passing `kms_key` `encryption_option`.

**Comment by laughingman7743** [comment]
It is okay. I will investigate.

**Comment by laughingman7743** [comment]
Is it possible to encrypt the query results when using Boto3?
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html
If you seem to be able to do it, please share that sample code.

**Comment by chgangaraju** [comment]
This following code is working for me 

    client = boto3.client('athena')
    response = client.start_query_execution(
        QueryString=sql_query',
        QueryExecutionContext={
            'Database': database
        },
        ResultConfiguration={
            'OutputLocation': s3_staging_dir,
            'EncryptionConfiguration': {
                'EncryptionOption': 'SSE_KMS',
                'KmsKey': kms_key_arn
            }
        }
    )

**Comment by chgangaraju** [comment]
It is working as expected with PyAthena also.

    connection = connect(
        s3_staging_dir='s3://' + athena_results_s3_bucket + '/athena_results',
        region_name=region,
        encryption_option='SSE_KMS',
        kms_key=kms_key
    )
    cursor = connection.cursor()
    cursor.execute(sql_query)

![image](https://user-images.githubusercontent.com/3478425/53554688-53ca9880-3b66-11e9-89a5-c1f424a6d11f.png)

But the results inside `s3_staging_dir` is not encrypted. But it is actualy encrypted at `s3://aws-athena-query-results-<account_id>-<region>/Unsaved/2019/02/28/0a7d28b4-d785-41e7-b0bd-40fc5a87c05e.csv`

Is there any way to encrypt this as well?
