### ISSUE TITLE
How to specify output bucket for query results in s3? 

### ISSUE THREAD

**Issue by otmezger** [laughingman7743/PyAthena#88]
Hi, we are moving frmo pyathenajdbc to pyathena, but we are trying to specify the `S3OutputLocation` parameter. We need it in our code. is this possible for this library? 

thanks.

**Comment by otmezger** [comment]
see https://docs.aws.amazon.com/athena/latest/APIReference/API_ResultConfiguration.html#athena-Type-ResultConfiguration-OutputLocation

and https://github.com/laughingman7743/PyAthenaJDBC/blob/master/pyathenajdbc/connection.py#L127

**Comment by jkleint** [comment]
Use the `s3_staging_dir` option to `connect()`.
https://pypi.org/project/PyAthena/

**Comment by otmezger** [comment]
Hi @jkleint, sorry for not being more explicit. the `s3_staging_dir` option, as far as I know, is for the source of the data to run the query against as configured in the athena/glue table.

What I'm looking for is the location of the output files that athena generates (csv, txt, meta). I want to store them in a bucket other than the data itself.

**Comment by otmezger** [comment]
@hero0926 [here](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html) is the documentation from botocore and athena. it seems to have a `Resultconfiguration` 

```
'ResultConfiguration': {
            'OutputLocation': 'string',
            'EncryptionConfiguration': {
                'EncryptionOption': 'SSE_S3'|'SSE_KMS'|'CSE_KMS',
                'KmsKey': 'string'
            }
        },
```

It is being used here: https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L66

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/common.py#L125
This is because the option name in the early release JDBC driver was `s3_staging_dir`.

**Comment by otmezger** [comment]
Thanks @laughingman7743, I get it. So  `s3_staging_dir` in `connect` means the root of the data, and in `execute` means `OutputLocation`

is this correct?

**Comment by laughingman7743** [comment]
You can also change it when you run the query.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/cursor.py#L43

**Comment by rinatio** [comment]
@laughingman7743 would `AWS_ATHENA_S3_STAGING_DIR` environment also do it?

**Comment by laughingman7743** [comment]
Yes!
