### ISSUE TITLE
retry capability in pyathena

### ISSUE THREAD

**Issue by rakekris** [laughingman7743/PyAthena#97]
Hi Team

Can you please add retry capability in pyathena. Since athena is serverless, we might get failures based on the load on AWS. If this feature is already present, Can you please share the details on how to use.

Thank you

**Comment by laughingman7743** [comment]
Retry is already implemented.
API requests use this wrapper method.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/util.py#L43

Retry config class can be passed to connection object.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L40
This is the retry config class.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/util.py#L32

**Comment by rakekris** [comment]
@laughingman7743 thank you

**Comment by dave-kielpinski-circleci** [comment]
could these links be replaced by permalinks please? they are broken

**Comment by laughingman7743** [comment]
API requests use this wrapper method.
https://github.com/laughingman7743/PyAthena/blob/v1.10.8/pyathena/util.py#L327
Retry config class can be passed to connection object.
https://github.com/laughingman7743/PyAthena/blob/v1.10.8/pyathena/connection.py#L60
This is the retry config class.
https://github.com/laughingman7743/PyAthena/blob/v1.10.8/pyathena/util.py#L311

**Comment by dreamiter** [comment]
Hi @laughingman7743  - I'm trying to pass in a custom `RetryConfig` as follows, but it does not seem to work. Do you have any working examples?

Here's what I'm doing:
```
class RetryConfig:
    """
    Custom retry configuration class
    """

    def __init__(
        self,
        exceptions=(
            "ThrottlingException",
            "TooManyRequestsException",
            "NotSupportedError",
            "OperationalError",
        ),
        attempt=3,
        multiplier=1,
        max_delay=100,
        exponential_base=2,
    ):
        """
        Initialize the custom retry configuration class
        """
        self.exceptions = exceptions
        self.attempt = attempt
        self.multiplier = multiplier
        self.max_delay = max_delay
        self.exponential_base = exponential_base


conn = connect(
        s3_staging_dir=S3_STAGING_DIR,
        region_name=REGION,
        retry_config=RetryConfig(),
    )
```

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L264
retry_config is passed to the cursor class. 🤔
