### ISSUE TITLE
make s3_staging_dir optional when work group is passed

### ISSUE THREAD

**Issue by nitin-kakkar** [laughingman7743/PyAthena#99]
**Since query result location can be configured at the workgroup level, would it be possible to make the s3_staging_dir parameter optional.**

excerpt from boto3 documentation 
**

> ResultConfiguration (dict) --
> Specifies information about where and how to save the results of the query execution. If the query runs in a workgroup, then workgroup's settings may override query settings. This affects the query results location. The workgroup settings override is specified in EnforceWorkGroupConfiguration (true/false) in the WorkGroupConfiguration. See WorkGroupConfiguration$EnforceWorkGroupConfiguration .
> 
> OutputLocation (string) --
> The location in Amazon S3 where your query results are stored, such as s3://path/to/query/bucket/ . To run the query, you must specify the query results location using one of the ways: either for individual queries using either this setting (client-side), or in the workgroup, using WorkGroupConfiguration . If none of them is set, Athena issues an error that no output location is provided. For more information, see Query Results . If workgroup settings override client-side settings, then the query uses the settings specified for the workgroup. See WorkGroupConfiguration$EnforceWorkGroupConfiguration .

**

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L46
